// PAGES METADATA
const PAGES = [
  {
    id: 'fashion',
    name: 'Fashion & Lifestyle',
    tagline: 'Style for everyone',
    heroTitle: 'Elevate your everyday',
    heroHighlight: 'style',
    heroDescription: 'From everyday essentials to statement pieces — discover top-rated picks across fashion, beauty, and home decor.',
    categories: ['All', 'Women Undergarments', 'Women Makeup', 'Skin Care', 'Women Dresses', 'Men Dresses', 'Hair Products', 'Home Decoration']
  },
  {
    id: 'tech',
    name: 'Tech Products',
    tagline: 'Smart living, simplified',
    heroTitle: 'The latest tech',
    heroHighlight: 'worth buying',
    heroDescription: 'Handpicked gadgets, kitchen tech, and accessories that make everyday life smoother and smarter.',
    categories: ['All', 'Tech Gadgets', 'Kitchen Accessories', 'Room Accessories', 'Tech Tools', 'Speakers', 'Bluetooth Devices']
  },
  {
    id: 'gaming',
    name: 'Gaming Products',
    tagline: 'Level up your setup',
    heroTitle: 'Build your dream',
    heroHighlight: 'gaming setup',
    heroDescription: 'Everything from pro-grade peripherals to ambient lighting — curated for gamers who want the best.',
    categories: ['All', 'Mouse', 'Storage', 'Xbox Accessories', 'Desk Pads', 'PC Accessories', 'Chair', 'Monitors', 'Merchandise', 'Collectables', 'Room Light', 'Games', 'Switch Accessories']
  },
  {
    id: 'fitness',
    name: 'Fitness Products',
    tagline: 'Train harder, recover smarter',
    heroTitle: 'Gear that moves',
    heroHighlight: 'with you',
    heroDescription: 'Weights, wearables, supplements, and outdoor gear — everything you need to hit your goals.',
    categories: ['All', 'Weights', 'Travel', 'Machines', 'Compact', 'Supplements', 'Tracking Device', 'Outdoor', 'Accessories', 'Flexible Training', 'Water Bottles', 'Strength', 'Home Workout', 'CrossFit', 'Wearable', 'Equipment']
  }
];

// SAMPLE PRODUCTS
const PRODUCTS = [
 {
    id: 'f1-e',
    page: 'fashion',
    title: 'RUXIA Womens Boyshort Panties Seamless Nylon Underwear',
    description: 'RUXIA seamless nylon boyshort panties offer lightweight stretch, tagless comfort, and a smooth no-show fit under any clothing.',
    image: 'https://m.media-amazon.com/images/I/81v8g-S+soL._AC_SX679_.jpg',
    price: 19.99,
    originalPrice: 38.99,
    rating: 4.5,
    reviews:  2465,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/01L2rfFD',
    featured: true,
  },
  {
    id: 'f1-d',
    page: 'fashion',
    title: 'YIANNA Fajas Colombianas Shapewear for Women',
    description: 'Achieve a smooth, contoured silhouette with YIANNA Fajas Colombianas Shapewear, featuring targeted firm compression for waist and tummy sculpting.',
    image: 'https://m.media-amazon.com/images/I/61a2FKd6pLL.jpg',
    price: 37.99,
    originalPrice: 42.99,
    rating: 4.5,
    reviews:  14732,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/05A3DsvS',
    featured: true,
  },
  {
    id: 'f1-c',
    page: 'fashion',
    title: 'Cosmetics Nose Large Hydrocolloid Pore Strips',
    description: 'Mighty Patch Hero Cosmetics Nose Large Hydrocolloid Pore Strips, 10 Ct | Pimple Patches for Overnight, Dermatologist Approved, Pimple Stickers',
    image: 'https://m.media-amazon.com/images/I/71A2Iw8Eh7L._SX679_.jpg',
    price: 13.99,
    originalPrice: 29.99,
    rating: 4.5,
    reviews:  14732,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/08Y9ONr0',
    featured: true,
  },
  {
    id: 'f1-b',
    page: 'fashion',
    title: 'LivDry Adult XXL Incontinence Underwear',
    description: 'Features a super-absorbent gel core capable of holding up to 50.5 oz (approx. 1,492 mL) of fluid. It quickly locks away moisture to keep skin dry and helps reduce odor.',
    image: 'https://m.media-amazon.com/images/I/71K5vwfHncL._AC_SX679_.jpg',
    price: 77.99,
    originalPrice: 99.55,
    rating: 4.6,
    reviews: 10811,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/0ebTBivX',
    featured: true,
  },
  {
    id: 'f1',
    page: 'fashion',
    title: 'Amazon Essentials Womens Cotton Spandex Bikini Brief Underwear (Available in Plus Size)',
    description: 'FIT: Bikini style panties sit at the low hip with full back coverage COTTON SPANDEX: Soft, smooth cotton blend. This breathable lightweight natural fabric feels soft  with you',
    image: 'https://m.media-amazon.com/images/I/81ERB4kK5gL._AC_SY879_.jpg',
    price: 11.99,
    originalPrice: 24.55,
    rating: 4.6,
    reviews: 10811,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/0gUH4r5w',
    featured: true,
  },
  {
    id: 'f2-e',
    page: 'fashion',
    title: 'Bliss Drench & Quench Hyaluronic Acid Face Moisturizer',
    description: 'Web: Bliss Drench & Quench cream-to-water moisturizer delivers intense, weightless hydration using 4 hyaluronic acid forms for glowing skin.',
    image: 'https://m.media-amazon.com/images/I/61eybGOJepL._SL1500_.jpg',
    price: 25.00,
    originalPrice: 28.00,
    rating: 4.4,
    reviews: 3458,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/09YSzLm4',
  },
  {
    id: 'f2-d',
    page: 'fashion',
    title: 'Shark CryoGlow LED Face Mask in Blue Frost, FW312',
    description: 'Rejuvenate your skin with the Shark CryoGlow LED Face Mask, featuring targeted light therapy and cooling technology to reduce inflammation and restore your natural glow.',
    image: 'https://m.media-amazon.com/images/I/71DwJryUsAL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 350.00,
    originalPrice: 399.00,
    rating: 4.4,
    reviews: 5402,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/07DyCSEf',
  },
  {
    id: 'f2-c',
    page: 'fashion',
    title: 'First Aid Beauty Ultra Repair Cream',
    description: 'First Aid Beauty Ultra Repair Cream is an ultra-rich, fragrance-free face and body moisturizer containing 0.5% Colloidal Oatmeal.',
    image: 'https://m.media-amazon.com/images/I/71eLojzJ+EL._SX522_.jpg',
    price: 35.00,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 5402,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/09xUoIPo',
  },
  {
    id: 'f2-b',
    page: 'fashion',
    title: 'SimplyVital Face Moisturizer Retinol Collagen Hyaluronic Acid Cream 1.7 oz ',
    description: 'Achieve smooth, hydrated, and visibly firm skin day and night. Its lightweight, silky formula deeply moisturizes without feeling heavy. Perfect for face and neck care!',
    image: 'https://m.media-amazon.com/images/I/51dYkEzrtDL._SY300_SX300_QL70_FMwebp_.jpg',
    price: 23.00,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 36402,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/05sxr7fl',
  },
    {
    id: 'f2',
    page: 'fashion',
    title: 'Revision Skincare D·E·J Eye Cream',
    description: 'an advanced, comprehensive eye treatment designed to firm, lift, and smooth the total eye area by targeting the dermal-epidermal junction (D·E·J).',
    image: 'https://m.media-amazon.com/images/I/614xWE5O-bL._SX679_.jpg',
    price: 125.99,
    originalPrice: 250.99,
    rating: 4.5,
    reviews: 3421,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/0aDtLv0H',
  },
  {
    id: 'f3-d',
    page: 'fashion',
    title: 'Long Sleeve Sun Protection Safari ',
    description: 'Elevate your wardrobe with the IHOT Womens V-Neck Faux Wrap Bodycon Dress. Designed with a flattering deep V-neckline.',
    image: 'https://m.media-amazon.com/images/I/71vsqYVhcHL._AC_SX679_.jpg',
    price: 37.99,
    originalPrice: 45.99,
    rating: 4.8,
    reviews: 3575,
    category: 'Women Dresses',
    affiliateLink: 'https://a.co/d/00PIQOKh',
    featured: true,
  },
   {
    id: 'f3-c',
    page: 'fashion',
    title: 'IHOT Womens 2026 Sexy V Neck ',
    description: 'Elevate your wardrobe with the IHOT Womens V-Neck Faux Wrap Bodycon Dress. Designed with a flattering deep V-neckline.',
    image: 'https://m.media-amazon.com/images/I/516AUCSViWL._AC_SY879_.jpg',
    price: 43.99,
    originalPrice: 45.99,
    rating: 4.7,
    reviews: 2967,
    category: 'Women Dresses',
    affiliateLink: 'https://a.co/d/0ggJuhS6',
    featured: true,
  },
  {
    id: 'f3-b',
    page: 'fashion',
    title: 'GRECERELLE 2026 Women Year-Round Casual Maxi',
    description: 'The GRECERELLE Long Maxi Dress with Pockets is your new go-to for every season. Featuring a loose, flowy fit, chic side slit, and zero wrinkles.',
    image: 'https://m.media-amazon.com/images/I/61ceyasLBOL._AC_SY879_.jpg',
    price: 19.99,
    originalPrice: 26.99,
    rating: 4.7,
    reviews: 2967,
    category: 'Women Dresses',
    affiliateLink: 'https://a.co/d/08wi48XV',
    featured: true,
  },
  {
    id: 'f3',
    page: 'fashion',
    title: 'WIHOLL Summer Dresses Cap Sleeve',
    description: 'The WIHOLL Summer Cap Sleeve Maxi Dress is a soft, lightweight polyester-spandex casual long dress featuring a classic crew neck, cap sleeves vacations and summer wear.',
    image: 'https://m.media-amazon.com/images/I/71XHIDZUoqL._AC_SY879_.jpg',
    price: 12.99,
    originalPrice: 14.99,
    rating: 4.7,
    reviews: 2967,
    category: 'Women Dresses',
    affiliateLink: 'https://a.co/d/0hPy1MGB',
    featured: true,
  },
  {
    id: 'f4-e',
    page: 'fashion',
    title: 'Mens Luxury Brand Print Silk Satin Design Button Down Dress Shirt',
    description: 'Web: Alex Vando mens regular fit long sleeve dress shirt offers flexible stretch fabric, wrinkle resistance, and polished daily style.',
    image: 'https://m.media-amazon.com/images/I/81Lrucbm5IL._AC_SX679_.jpg',
    price: 14.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviews: 3462,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/0extbeEu',
  },
   {
    id: 'f4-d',
    page: 'fashion',
    title: 'Mens Luxury Brand Print Silk Satin Design Button Down Dress Shirt',
    description: 'Crafted from silky, lightweight fabric with an eye-catching graphic design, it offers a regular-fit tailored silhouette that transitions effortlessly from night events to high-fashion street style.',
    image: 'https://m.media-amazon.com/images/I/81jWwiB6qSL._AC_SX679_.jpg',
    price: 54.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviews: 1006,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/06xwQR9E',
  },
  {
    id: 'f4-c',
    page: 'fashion',
    title: 'Mens 2 Pieces Outfits Casual Polo Shirt and Shorts Set Collar Athletic Jogging Summer Tracksuit',
    description: 'Premium Fabric:The mens tracksuits set is crafted from high-quality fabric that is soft yet elastic,lightweight and breathable,ensuring you can move freely during your workout',
    image: 'https://m.media-amazon.com/images/I/71rg2sDkLiL._AC_SY879_.jpg',
    price: 34.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 16046,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/01UoSqWZ',
  },
   {
    id: 'f4-b',
    page: 'fashion',
    title: 'COOFANDY Men\'s Slim Fit Suit',
    description: 'a lightweight, breathable button-up top made from a cotton-linen rayon blend, featuring a relaxed fit, short sleeves, and a classic collar designed for beachwear, summer vacations, or casual everyday outfits.',
    image: 'https://m.media-amazon.com/images/I/81+oQBvBR-L._AC_SY879_.jpg',
    price: 29.99,
    originalPrice: 34.99,
    rating: 4.6,
    reviews: 16046,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/0bcBDGA3',
  },
    {
    id: 'f4',
    page: 'fashion',
    title: 'COOFANDY Mens Linen Shirts Short Sleeve Casual Shirts',
    description: 'a lightweight, breathable button-up shirt crafted from a cotton-linen blend, designed for comfortable everyday wear, beach outings, and summer events.',
    image: 'https://m.media-amazon.com/images/I/81TSrTXy8TL._AC_SY879_.jpg',
    price: 29.99,
    originalPrice: 31.99,
    rating: 4.4,
    reviews: 876,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/06eSEiA8',
  },
  {
    id: 'f5-e',
    page: 'fashion',
    title: 'Shapiro MD Hair Growth Experts Natural Hair Kit for Thicker Looking Hair',
    description: 'Web: Shapiro MD Natural Hair Kit uses doctor-formulated ingredients to block DHT, combat thinning, and promote visibly thicker, fuller hair.',
    image: 'https://m.media-amazon.com/images/I/61efxz+-qrL._SX679_.jpg',
    price: 74.99,
    originalPrice: 99.99,
    rating: 4.3,
    reviews: 2789,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/0aOlV9DJ',
  },
  {
    id: 'f5-d',
    page: 'fashion',
    title: 'MAREE Deep Conditioning Hair Mask for Damaged Hair Treatment',
    description: 'Nourish and repair dry, brittle strands with the MAREE Deep Conditioning Hair Mask. Infused with natural oils and essential nutrients, this intensive mask restores moisture, smooths frizz, and strengthens damaged hair for a silky, healthy shine.',
    image: 'https://m.media-amazon.com/images/I/51Q-4STYtjL._SY300_SX300_QL70_FMwebp_.jpg',
    price: 26.99,
    originalPrice: 34.99,
    rating: 4.3,
    reviews: 2789,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/0h771FLt',
  },
  {
    id: 'f5-c',
    page: 'fashion',
    title: 'Karseell Collagen Hair Mask for Dry, Frizzy, Damaged Hair ',
    description: 'All Hair Types: Suitable for all hair types dry/damaged/frizzy; fine hair caution; suitable for color treated and chemically processed hair; intended for hair lengths and ends and used away from scalp',
    image: 'https://m.media-amazon.com/images/I/71zGjIPmz8L._SL1500_.jpg',
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.3,
    reviews: 2789,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/06FSyZZd',
  },
   {
    id: 'f5-b',
    page: 'fashion',
    title: 'Nutrafol Men Hair Serum for Thinning Hair',
    description: 'Apply once daily directly to the scalp. Designed to work alongside daily hair growth supplements for optimal results.',
    image: 'https://m.media-amazon.com/images/I/616yx5sb7jL._SX522_.jpg',
    price: 49.99,
    originalPrice: 74.99,
    rating: 4.3,
    reviews: 2789,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/06ocnGxi',
  },
    {
    id: 'f5',
    page: 'fashion',
    title: 'Sulfate Free Hair Growth Product',
    description: 'a sulfate-free, color-safe conditioner that detangles, thickens, and nourishes fine or thinning hair without weighing it down.',
    image: 'https://m.media-amazon.com/images/I/51V5ikw1c9L._SX522_.jpg',
    price: 46.00,
    originalPrice: 54.99,
    rating: 4.6,
    reviews: 2104,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/07xeGLXD',
  },
  {
    id: 'f6-d',
    page: 'fashion',
    title: 'EUDELE Adhesive Shower Caddy',
    description: 'EUDELE adhesive shower caddy provides rustproof stainless steel storage, strong damage-free wall mounting, and deep organizer space for bathroom essentials.',
    image: 'https://m.media-amazon.com/images/I/81S6FPdEHWL._AC_SX679_.jpg',
    price: 19.99,
    originalPrice: 27.99,
    rating: 4.8,
    reviews: 2468,
    category: 'Home Decoration',
    affiliateLink: 'https://a.co/d/065n8XWB',
  },
  {
    id: 'f6-c',
    page: 'fashion',
    title: 'Astercook Deep-Carbonized Bamboo Cutting Boards for Kitchen with Wood Storage Stand',
    description: 'Upgrade your kitchen with the Astercook Deep-Carbonized Bamboo Cutting Board Set, complete with a convenient wooden storage stand. Crafted from durable, deep-carbonized bamboo for superior water resistance and strength, these boards provide a hygienic, knife-friendly surface for all your prep work.',
    image: 'https://m.media-amazon.com/images/I/91xky+JYmZL._AC_SL1500_.jpg',
    price: 23.99,
    originalPrice: 39.99,
    rating: 4.5,
    reviews: 847,
    category: 'Home Decoration',
    affiliateLink: 'https://a.co/d/0i5hNtHd',
  },
  {
    id: 'f6-b',
    page: 'fashion',
    title: 'TCL 52" Black Flush Mount Ceiling Fan with Light & Remote',
    description: 'Customizable Lighting: This ceiling fan comes with a 20W dimmable LED light, offering a more energy-efficient. The modern ceiling fan features three color temperatures—3000K warm light, 4000K natural ligh',
    image: 'https://m.media-amazon.com/images/I/51f-pn9cjeL._AC_SL1500_.jpg',
    price: 109.99,
    originalPrice: 159.99,
    rating: 4.5,
    reviews: 847,
    category: 'Home Decoration',
    affiliateLink: 'https://a.co/d/0e79Noxm',
  },
  {
    id: 'f6',
    page: 'fashion',
    title: 'Premium Aesthetic Faux Books for Room Decor',
    description: 'Made of durable, lightweight cardboard with printed matte covers. The books are completely hollow, do not open, have no interior pages, and do not provide storage space.',
    image: 'https://m.media-amazon.com/images/I/71QoYHSuC6L._AC_SL1500_.jpg',
    price: 24.99,
    originalPrice: 59.99,
    rating: 4.5,
    reviews: 847,
    category: 'Home Decoration',
    affiliateLink: 'https://a.co/d/05YKcRwn',
  },
  {
    id: 'f7-d',
    page: 'fashion',
    title: 'Contour Stick Makeup Collection',
    description: 'Dual-ended contour stick collection features creamy, blendable shades for effortless face sculpting, natural highlighting, and long-lasting definition.',
    image: 'https://m.media-amazon.com/images/I/71T182tOnsL._SX679_.jpg',
    price: 99.99,
    originalPrice: 120.99,
    rating: 4.7,
    reviews: 34379,
    category: 'Women Makeup',
    affiliateLink: 'https://a.co/d/0ewVzaoC',
  },
   {
    id: 'f7-c',
    page: 'fashion',
    title: 'Loose Powder for Under Eye Brightening & Dark Circles',
    description: 'Instantly revive tired eyes with bareMinerals Well Rested Under Eye Brightener SPF 20. This lightweight loose mineral powder effortlessly conceals dark circles, brightens the under-eye area, and provides mineral sun protection in a vegan, skin-loving formula.',
    image: 'https://m.media-amazon.com/images/I/71sP1Z0jhPL._SX522_.jpg',
    price: 27.99,
    originalPrice: 39.99,
    rating: 4.2,
    reviews: 382,
    category: 'Women Makeup',
    affiliateLink: 'https://a.co/d/0fXth7D8',
  },
  {
    id: 'f7-b',
    page: 'fashion',
    title: 'Prime Prometics PrimeLash Mascara for Older Woman (Black) | Volumizing, Incredible Length in 2 Coats, Long-Stay, Zero Clumps, Hypoallergenic',
    description: 'THICK, DEFINED AND LIFTED LASHES - In two clean coats. You will have lashes that make You look like a Million dollars. Thanks to the effective magic wand and formula duo.',
    image: 'https://m.media-amazon.com/images/I/51rjD1DyfpL._SX679_.jpg',
    price: 28.99,
    originalPrice: 36.99,
    rating: 4.6,
    reviews: 78382,
    category: 'Women Makeup',
    affiliateLink: 'https://a.co/d/04htNIAO',
  },
  {
    id: 'f7',
    page: 'fashion',
    title: 'LAURA GELLER Baked Balance-n-Brighten Powder',
    description: 'a lightweight, baked powder foundation handcrafted in Italy designed to self-adjust to your skin tone and even out complexion.',
    image: 'https://m.media-amazon.com/images/I/71RaNMySLgL._SL1500_.jpg',
    price: 32.99,
    originalPrice: 36.99,
    rating: 4.9,
    reviews: 21309,
    category: 'Women Makeup',
    affiliateLink: 'https://a.co/d/07kdaTZk',
  },

  // ===== TECH PRODUCTS =====
  {
    id: 't1-d',
    page: 'tech',
    title: ' Bluetooth Music Receiver',
    description: 'Bluetooth 5.3 music receiver delivers low-latency wireless audio streaming, dual-device pairing, and ultra-stable connectivity for home stereos and car speakers.  ',
    image: 'https://m.media-amazon.com/images/I/61s-feb9ruL._AC_SL1500_.jpg',
    price: 99.99,
    originalPrice: 109.99,
    rating: 4.9,
    reviews: 2421,
    category: 'Bluetooth Devices',
    affiliateLink:'https://a.co/d/0a2uK7p8',
    featured: true,
  },
   {
    id: 't1-c',
    page: 'tech',
    title: 'Perytong Sleep Headphones Wireless',
    description: 'Perytong wireless sleep headphones headband delivers ultra-soft comfort, flat speakers, and long battery life for peaceful sleep and workouts.',
    image: 'https://m.media-amazon.com/images/I/810p2QGLVOL._AC_SL1500_.jpg',
    price: 15.99,
    originalPrice: 19.99,
    rating: 4.9,
    reviews: 2421,
    category: 'Bluetooth Devices',
    affiliateLink:'https://a.co/d/08jI6rrm',
    featured: true,
  },
  {
    id: 't1-b',
    page: 'tech',
    title: 'Esinkin Bluetooth Audio Adapter',
    description: 'Works with most device: Bluetooth enabled device including smartphones, tablets, computers, laptops upon and any powered PC speakers.',
    image: 'https://m.media-amazon.com/images/I/61HcKHv9M2L._AC_SX679_.jpg',
    price: 14.99,
    originalPrice: 16.99,
    rating: 4.8,
    reviews: 3421,
    category: 'Bluetooth Devices',
    affiliateLink:'https://a.co/d/0eyYtTzC',
    featured: true,
  },
  {
    id: 't1',
    page: 'tech',
    title: 'Apple MFi Certified Wallet Tracker Smart Card',
    description: 'an ultra-thin (2.5mm), credit card-shaped item locator that integrates natively with Apples Find My app to help you track lost wallets.',
    image: 'https://m.media-amazon.com/images/I/71epei5xfnL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 14.99,
    originalPrice: 16.99,
    rating: 4.8,
    reviews: 3421,
    category: 'Bluetooth Devices',
    affiliateLink:'https://a.co/d/01mPpiTq',
    featured: true,
  },
  {
    id: 't2-d',
    page: 'tech',
    title: 'LabCharge Purifier for Home & Bedroom',
    description: 'LabCharge plug-in ionic air purifier delivers compact, filter-free air cleansing that silently eliminates dust, odors, and pet dander in small spaces.  ',
    image: 'https://m.media-amazon.com/images/I/71A+q30FAiL._AC_SX679_.jpg',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.6,
    reviews: 3457,
    category: 'Tech Gadgets',
    affiliateLink: 'https://a.co/d/0b9sTBgN',
    featured: true,
  },
   {
    id: 't2-c',
    page: 'tech',
    title: 'GIGASTONE 128GB Micro SD Card 2-Pack',
    description: 'GIGASTONE 128GB Micro SD Card 2-pack offers fast transfer speeds, durable storage, and reliable expansion for cameras and devices.',
    image: 'https://m.media-amazon.com/images/I/6135X0P2cML._AC_SX679_.jpg',
    price: 68.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviews: 6460,
    category: 'Tech Gadgets',
    affiliateLink: 'https://a.co/d/07fB2lTU',
    featured: true,
  },
   {
    id: 't2-b',
    page: 'tech',
    title: 'AROEVE Air Purifiers for Bedroom with Sleep Mode Speed Control-MK01A',
    description: 'High Circulation Rate: With dual-channel and 360-degree air inlets technology, AROEVE air purifier refreshes the air per hour in rooms.',
    image: 'https://m.media-amazon.com/images/I/61A4iO11nrL._AC_SX679_.jpg',
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 2180,
    category: 'Tech Gadgets',
    affiliateLink: 'https://a.co/d/0e5Y5M1n',
    featured: true,
  },
  {
    id: 't2',
    page: 'tech',
    title: 'LISEN Retractable Car Charger',
    description: 'an 84-watt fast-charging cigarette lighter adapter featuring two 31.5-inch retractable cables (USB-C & Lightning), dual USB ports.',
    image: 'https://m.media-amazon.com/images/I/71Ryl5xKbuL._AC_SL1500_.jpg',
    price: 16.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviews: 2180,
    category: 'Tech Gadgets',
    affiliateLink: 'https://a.co/d/0hJ2nAVP',
    featured: true,
  },
  {
    id: 't3-d',
    page: 'tech',
    title: 'Refrigerator Water Filter',
    description: 'Refrigerator water filters remove contaminants, chlorine, and odors to deliver fresh, clean water and ice right from your fridge.',
    image: 'https://m.media-amazon.com/images/I/61J-XpQQXDL._AC_SX679_.jpg',
    price: 30.99,
    originalPrice: 36.99,
    rating: 4.6,
    reviews: 27546,
    category: 'Kitchen Accessories',
    affiliateLink: 'https://a.co/d/0gaJcGez',
    featured: true,
  },
   {
    id: 't3-c',
    page: 'tech',
    title: 'Cutluxe Brisket Knife, 12" Carving & Slicing Knife for Meat & BBQ',
    description: 'Cutluxe 12-inch brisket slicing knife delivers razor-sharp precision, effortless meat carving, and maximum comfort for ultimate BBQ prep.',
    image: 'https://m.media-amazon.com/images/I/81bV4GT5Y8L._AC_SL1500_.jpg',
    price: 44.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviews: 6532,
    category: 'Kitchen Accessories',
    affiliateLink: 'https://a.co/d/075IwMtn',
    featured: true,
  },
  {
    id: 't3-b',
    page: 'tech',
    title: 'Steam Cleaner',
    description: '6-Level Adjustable Touch Control: Simply press the “+” or “-” buttons on the handheld steam cleaner to easily switch between six steam. ',
    image: 'https://m.media-amazon.com/images/I/710EPs-7hML._AC_SL1500_.jpg',
    price: 49.99,
    originalPrice: 68.99,
    rating: 4.7,
    reviews: 1532,
    category: 'Kitchen Accessories',
    affiliateLink: 'https://a.co/d/01b6Yxua',
    featured: true,
  },
  {
    id: 't3',
    page: 'tech',
    title: 'Handheld Steam Cleaner',
    description: 'a chemical-free, pressurized steamer delivering 230°F continuous steam with a 350ML tank and 14 accessories for deep cleaning kitchen.',
    image: 'https://m.media-amazon.com/images/I/61ixIb6YrAL._AC_SX679_.jpg',
    price: 39.99,
    originalPrice: 45.99,
    rating: 4.7,
    reviews: 1532,
    category: 'Kitchen Accessories',
    affiliateLink: 'https://a.co/d/02g4JMaD',
    featured: true,
  },
  {
    id: 't4-d',
    page: 'tech',
    title: 'Slice Slim Toaster',
    description:  'Compact 2-slice slim toaster fits perfectly in small kitchens while delivering crisp, golden-brown toast in seconds.',
    image: 'https://m.media-amazon.com/images/I/71zZ0tSkfHL._AC_SL1500_.jpg',
    price: 16.09,
    originalPrice: 44.99,
    rating: 4.5,
    reviews: 19246,
    category: 'Room Accessories',
    affiliateLink: 'https://a.co/d/0h8qshwJ',
  },
  {
    id: 't4-c',
    page: 'tech',
    title: 'The Original Katchy Indoor Insect Trap ',
    description:  'Original Katchy indoor insect trap captures gnats, fruit flies, and mosquitoes using UV light, fan suction, and sticky boards.',
    image: 'https://m.media-amazon.com/images/I/81ALQYCQGwL._AC_SL1500_.jpg',
    price: 39.99,
    originalPrice: 44.99,
    rating: 4.5,
    reviews: 932,
    category: 'Room Accessories',
    affiliateLink: 'https://a.co/d/00RcWeg4',
  },
  {
    id: 't4-b',
    page: 'tech',
    title: 'DREO 3L Humidifiers for Bedroom',
    description:  'Enjoy a serene sleep with DREOs 26dB (in Sleep Mode) whisper-quiet air humidifier, crafted for your babys ultimate comfort.',
    image: 'https://m.media-amazon.com/images/I/618s2JAQmXL._AC_SL1500_.jpg',
    price: 28.99,
    originalPrice: 39.99,
    rating: 4.5,
    reviews: 932,
    category: 'Room Accessories',
    affiliateLink: 'https://a.co/d/0ffVygh5',
  },
  {
    id: 't4',
    page: 'tech',
    title: 'Air Purifiers for Home',
    description: 'covers large rooms up to 3,000 sq. ft. using a double-sided HEPA filtration system with a washable pre-filter, real-time PM2.5 air qen.',
    image: 'https://m.media-amazon.com/images/I/81KMChQ1-GL._AC_SX679_.jpg',
    price: 109.99,
    originalPrice: 139.99,
    rating: 4.5,
    reviews: 932,
    category: 'Room Accessories',
    affiliateLink: 'https://a.co/d/070YAy2x',
  },
  {
    id: 't5-d',
    page: 'tech',
    title: 'Endoscope Camera with Light',
    description: 'See inside tight pipes, car engines, and hidden spaces effortlessly with this crisp HD endoscope camera with bright LED lights!',
    image: 'https://m.media-amazon.com/images/I/61oRhqttqJL._AC_SX679_.jpg',
    price: 23.99,
    originalPrice: 30.99,
    rating: 4.5,
    reviews: 7201,
    category: 'Tech Tools',
    affiliateLink: 'https://a.co/d/0iCyVA6V',
  },
  {
    id: 't5-c',
    page: 'tech',
    title: 'ThePhotoStick® Omni 128GB Photo Backup for iPhone, Android and Computers',
    description: 'ThePhotoStick Omni 128GB automatically finds and backs up over 50,000 photos and videos across iPhone, Android, and computers.  ',
    image: 'https://m.media-amazon.com/images/I/61Nwje5iDGL._AC_SX679_.jpg',
    price: 84.99,
    originalPrice: 89.99,
    rating: 4.5,
    reviews: 945,
    category: 'Tech Tools',
    affiliateLink: 'https://a.co/d/04u89U9P',
  },
  {
    id: 't5-b',
    page: 'tech',
    title: 'Endoscope Camera with Light',
    description: 'Endoscope Camera with Light,1920P HD Borescope Tools with 8 Adjustable LED Lights, Endoscope with Semi-Rigid Snake Camera, Inspection Borescope for iOS and Android-16.4ft Single Lens',
    image: 'https://m.media-amazon.com/images/I/71anyb4JreL._AC_SX679_.jpg',
    price: 30.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviews: 2945,
    category: 'Tech Tools',
    affiliateLink: 'https://a.co/d/05tyHwkz',
  },
  {
    id: 't5',
    page: 'tech',
    title: 'Fanttik E2 Ultra Electric Screwdriver',
    description: 'a 270 RPM rechargeable precision driver set featuring 5 adjustable torque settings (up to 0.6N.m), 50 magnetic S2 steel bitsll appliances.',
    image: 'https://m.media-amazon.com/images/I/61q87lzcDhL._AC_SL1500_.jpg',
    price: 69.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviews: 2945,
    category: 'Tech Tools',
    affiliateLink: 'https://a.co/d/04ivYVxW',
  },
  {
    id: 't6-d',
    page: 'tech',
    title: 'Stereo Computer Speakers with Bluetooth',
    description: 'Level up your desktop setup with room-filling stereo sound and seamless Bluetooth streaming for music, movies, and gaming!',
    image: 'https://m.media-amazon.com/images/I/61k87LOX6tL._AC_SX679_.jpg',
    price: 59.99,
    originalPrice: 69.99,
    rating: 4.6,
    reviews: 7553,
    category: 'Speakers',
    affiliateLink: 'https://a.co/d/0aWw4l7l',
  },
  {
    id: 't6-c',
    page: 'tech',
    title: ' Active Bluetooth Bookshelf Speakers',
    description: 'Active Bluetooth bookshelf speakers deliver rich, room-filling sound, versatile wireless connectivity, and sleek design for modern home audio setups.',
    image: 'https://m.media-amazon.com/images/I/81CfJWhWw3L._AC_SL1500_.jpg',
    price: 229.99,
    originalPrice: 265.99,
    rating: 4.7,
    reviews: 6469,
    category: 'Speakers',
    affiliateLink: 'https://a.co/d/0ackaFSx',
  },
  {
    id: 't6-b',
    page: 'tech',
    title: 'dbsono Portable Bluetooth Speaker Wireless',
    description: '100W Peak, Bluetooth 6.0, Black | SoundPulse 2.0, Bass Boost, USB-C Audio, Multi-Speaker Pairing, Waterproof, TWS stereo for indoor and outdoor listening',
    image: 'https://m.media-amazon.com/images/I/81ZFinKGAjL._AC_SX679_.jpg',
    price: 139.99,
    originalPrice: 165.99,
    rating: 4.5,
    reviews: 1876,
    category: 'Speakers',
    affiliateLink: 'https://a.co/d/08ReEltQ',
  },
  {
    id: 't6',
    page: 'tech',
    title: 'Amazon Basics Stereo 2.0 Speakers for PC or Laptop with Volume Control',
    description: 'a compact, USB-powered desk speaker pair featuring 3.5mm AUX connectivity, in-line volume control, blue LED accent lighting, and bottom passive radiators for enhanced bass performance.',
    image: 'https://m.media-amazon.com/images/I/71VUfk4MzJL._AC_SL1500_.jpg',
    price: 23.99,
    originalPrice: 25.99,
    rating: 4.5,
    reviews: 1876,
    category: 'Speakers',
    affiliateLink: 'https://a.co/d/0gZ8jGoS',
  },
  
  // ===== GAMING PRODUCTS =====
  {
    id: 'g1-e',
    page: 'gaming',
    title: 'Gaming Mouse',
    description: 'Dominate every match with ultra-precise tracking, customizable RGB lighting, and zero-lag response built for total gaming control!',
    image: 'https://m.media-amazon.com/images/I/51BhB+GhmQL._AC_SY879_.jpg',
    price: 99.99,
    originalPrice: 109.00,
    rating: 4.5,
    reviews: 1457,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/073oTKze',
    featured: true,
  },
{
    id: 'g1-d',
    page: 'gaming',
    title: 'Gaming Keyboard and Mouse Wireless',
    description: 'Upgrade your setup with this Wireless Gaming Keyboard and Mouse combo, featuring high-speed connectivity, vibrant RGB lighting, and ergonomic precision.',
    image: 'https://m.media-amazon.com/images/I/7165L+SRfDL._AC_SL1500_.jpg',
    price: 54.99,
    originalPrice: 62.00,
    rating: 4.8,
    reviews: 2341,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/042EQhsV',
    featured: true,
  },
  {
    id: 'g1-c',
    page: 'gaming',
    title: 'Razer Basilisk V3 Pro Customizable RGB Wireless Gaming Mouse, Black',
    description: 'Elevate your gaming with the Razer Basilisk V3 Pro—a high-performance wireless gaming mouse featuring 10+1 programmable controls, Razer HyperScroll Tilt Wheel.',
    image: 'https://m.media-amazon.com/images/I/71L-flqtTwL._AC_SL1500_.jpg',
    price: 99.00,
    originalPrice: 159.00,
    rating: 4.8,
    reviews: 2341,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/090icyQh',
    featured: true,
  },
  {
    id: 'g1-b',
    page: 'gaming',
    title: ' Wireless Gaming Mouse - Black',
    description: 'The Logitech G PRO X Superlight 2 is an ultra-lightweight (60g), high-performance wireless esports gaming mouse featuring an advanced HERO 2 sensor with up to 44,000 DPI and hybrid LIGHTFORCE optical-mechanical switches.',
    image: 'https://m.media-amazon.com/images/I/51Cps60NQpL._AC_SL1500_.jpg',
    price: 144.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviews: 2341,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/0hpzBnyj',
    featured: true,
  },
  {
    id: 'g1',
    page: 'gaming',
    title: 'Wireless RGB Gaming Mouse',
    description: 'hybrid LIGHTFORCE optical-mechanical switches, 8-zone LIGHTSYNC RGB lighting, a HERO 25K sensor, 13 customizable controls, and up to 130 hours of battery life with USB-C and PowerPlay wireless charging compatibility.',
    image: 'https://m.media-amazon.com/images/I/61A0MX5s2xL._AC_SL1500_.jpg',
    price: 148.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviews: 876,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/04f9lNcN',
    featured: true,
  },
  {
    id: 'g2-e',
    page: 'gaming',
    title: 'Curved Ultrawide WQHD Monitor ',
    description: 'Transform your setup with a curved ultrawide WQHD monitor—delivering panoramic 1440p clarity, seamless multitasking, and total visual immersion!  ',
    image: 'https://m.media-amazon.com/images/I/71sPOWyMwVL._AC_SX679_.jpg',
    price: 197.99,
    originalPrice: 209.99,
    rating: 4.7,
    reviews: 3093,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/07Ei9pfm',
    featured: true,
  },
   {
    id: 'g2-d',
    page: 'gaming',
    title: 'Gaming Monitor',
    description: 'Premium KOORUI 34-inch WQHD curved gaming monitor delivers ultra-smooth 200Hz action and immersive 1000R visuals.',
    image: 'https://m.media-amazon.com/images/I/71u1rjiFxuL._AC_SX679_.jpg',
    price: 249.99,
    originalPrice: 359.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0iS3Ap30',
    featured: true,
  },
  {
    id: 'g2-c',
    page: 'gaming',
    title: ' Prime Gaming Monitor Display',
    description: 'Level up your setup with the Sceptre 24-inch Prime Gaming Monitor (E248B-FW165T). Engineered for competitive play, and Adaptive Sync to eliminate lag and screen tearing.',
    image: 'https://m.media-amazon.com/images/I/71VQX048EVL._AC_SX679_.jpg',
    price: 81.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0iEC5xv9',
    featured: true,
  },
    {
    id: 'g2-b',
    page: 'gaming',
    title: 'Amazon Basics 24 Inch (23.8 inch viewable) Monitor',
    description: 'a 1080p Full HD IPS display with a 100Hz refresh rate, built-in speakers, and VESA mount compatibility for office and casual entertainment use.',
    image: 'https://m.media-amazon.com/images/I/710ZLpqfQeL._AC_SY450_.jpg',
    price: 83.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0d3Z86PT',
    featured: true,
  },
  {
    id: 'g2',
    page: 'gaming',
    title: 'Office Monitor',
    description: 'a 1080p Full HD IPS display with a smooth 120Hz refresh rate, 1ms VRB response time and blue light filtering for comfortable daily productivity and light gaming.',
    image: 'https://m.media-amazon.com/images/I/71e5GgPXQzL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    price: 99.99,
    originalPrice: 149.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0gAGupN9',
    featured: true,
  },
  {
    id: 'g3-e',
    page: 'gaming',
    title: 'Duramont Ergonomic Office Chair',
    description: 'Say goodbye to back pain with the Duramont Ergonomic Office Chair—featuring total lumbar support, breathable mesh, and customizable adjustments for all-day desk comfort!',
    image: 'https://m.media-amazon.com/images/I/81tjwXjUWuL._AC_SL1500_.jpg',
    price: 279.00,
    originalPrice: 299.99,
    rating: 4.6,
    reviews: 2002,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/00fcdRou',
  },
  {
    id: 'g3-d',
    page: 'gaming',
    title: 'NEO CHAIR Office Desk Chair',
    description: 'NEO CHAIR office desk chair provides ergonomic lumbar support, breathable mesh, and smooth height adjustment for all-day comfort.',
    image: 'https://m.media-amazon.com/images/I/814KhDPD-YL._AC_SL1500_.jpg',
    price: 59.00,
    originalPrice: 81.99,
    rating: 4.6,
    reviews: 2002,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/0eaNekCL',
  },
  {
    id: 'g3-c',
    page: 'gaming',
    title: 'Lumbar Support Pillow for Office Chair',
    description: 'Say goodbye to back pain with this Ergonomic Lumbar Support Pillow. Designed to improve posture and relieve lower back pressure,.',
    image: 'https://m.media-amazon.com/images/I/81Qm1-Fja2L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 26.00,
    originalPrice: 50.99,
    rating: 4.6,
    reviews: 1098,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/02Q2GxlI',
  },
  {
    id: 'g3-b',
    page: 'gaming',
    title: 'GTPLAYER Gaming Chair',
    description: 'Upgrade your seating experience with the GTPLAYER Ergonomic Gaming Chair. Designed for long hours of gaming or work,k faux leather.',
    image: 'https://m.media-amazon.com/images/I/61phC8Ix9bL._AC_SX679_.jpg',
    price: 109.99,
    originalPrice: 169.99,
    rating: 4.6,
    reviews: 16698,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/0iVVT567',
  },
  {
    id: 'g3',
    page: 'gaming',
    title: 'TRALT Office Chair Ergonomic Desk Chair',
    description: 'a high-density molded foam seat, depth-adjustable lumbar support, a breathable mesh backrest, flip-up armrests, and a heavy-duty base supporting up to 330 lbs.',
    image: 'https://m.media-amazon.com/images/I/81OW9VpP4qL._AC_SL1500_.jpg',
    price: 139.99,
    originalPrice: 159.99,
    rating: 4.6,
    reviews: 1098,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/05AvMSrt',
  },
  {
    id: 'g4-e',
    page: 'gaming',
    title: 'Upgraded RGB Cooling Fan',
    description: 'Say goodbye to back pain with the Duramont Ergonomic Office Chair—featuring total lumbar support, breathable mesh, and customizable adjustments for all-day desk comfort!',
    image: 'https://m.media-amazon.com/images/I/71l7o2eefQL._AC_SL1500_.jpg',
    price: 37.99,
    originalPrice: 45.99,
    rating: 4.6,
    reviews: 1380,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0gKs7Mti',
  },
  {
    id: 'g4-d',
    page: 'gaming',
    title: 'MENEEA Cooling Fan Dust Proof',
    description: 'MENEEA cooling fan and dust proof kit prevents overheating and keeps dust out for peak console performance.',
    image: 'https://m.media-amazon.com/images/I/711VHA32kwL._SX522_.jpg',
    price: 34.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 2216,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0dETXwJM',
  },
   {
    id: 'g4-c',
    page: 'gaming',
    title: 'GameSir G7 SE Wired Controller',
    description: 'Master your gameplay with the GameSir G7 SE Wired Controller for Xbox Series X|S, Xbox One, and Windows 10/11. Built wd zero stick drift.',
    image: 'https://m.media-amazon.com/images/I/51iXILIT27L._SX522_.jpg',
    price: 44.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 3210,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0cUX2dlS',
  },
  {
    id: 'g4-b',
    page: 'gaming',
    title: 'GameSir G7 Pro Wired Controller for Xbox Series',
    description: 'Take control with the GameSir G7 Pro Controller, designed for Xbox Series X|S, Xbox One, PC, and Android. Engineered for ultra-precise inputs, on PC.',
    image: 'https://m.media-amazon.com/images/I/719XHbmvmBL._SX522_.jpg',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 3210,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0hkJzdhh',
  },
  {
    id: 'g4',
    page: 'gaming',
    title: 'Seagate 2TB Game Drive for Xbox',
    description: 'an officially licensed external USB 3.0 hard drive featuring 2TB of portable storage, built-in Xbox green LED light, and compatibility with Xbox One titles directly.',
    image: 'https://m.media-amazon.com/images/I/416kbEX-pVL._AC_SL1500_.jpg',
    price: 119.99,
    originalPrice: 139.99,
    rating: 4.7,
    reviews: 3210,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0aqCkwHW',
  },
  {
    id: 'g5-d',
    page: 'gaming',
    title: 'Night Lights LED Star Projector for Bedroom',
    description: 'Transform your bedroom into a breathtaking galaxy in seconds with this LED star projector—bringing calm vibes, customizable colors, and magical bedtime lighting!',
    image: 'https://m.media-amazon.com/images/I/81ASRJlhl3L._AC_SX679_.jpg',
    price: 33.99,
    originalPrice: 43.99,
    rating: 4.6,
    reviews: 10223,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/0bL89Kgr',
  },
  {
    id: 'g5-e',
    page: 'gaming',
    title: 'Led Desk Lamp for Office Home - Eye Caring Architect lamp',
    description: 'Illuminate your workspace with this 24W Dual-Screen LED Desk Lamp. Designed for dual-monitor setups, drafting, and studying, it features an eye-caring.',
    image: 'https://m.media-amazon.com/images/I/616md8tdywL._AC_SL1080_.jpg',
    price: 46.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/00mtROIz',
  },
  {
    id: 'g5-d',
    page: 'gaming',
    title: 'Govee RGBIC Smart Table Lamp 2, Touch Bedside Small Table Lamp (Corded)',
    description: 'Elevate your space with the Govee RGBIC Smart Table Lamp 2. Designed with advanced RGBIC technology to display multiple colors at once, this compact corded bedside lamp features intuitive touch controls, customizable lighting effects, and seamless app or voice control. Perfect for nightstands, gaming desks, or creating a cozy, colorful atmosphere anywhere in your home.',
    image: 'https://m.media-amazon.com/images/I/618yTEtHltL._AC_SL1500_.jpg',
    price: 63.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/0do989EV',
  },
  {
    id: 'g5-c',
    page: 'gaming',
    title: 'Govee RGBIC Floor Lamp Basic, 1000lm LED Corner Lamp, Black',
    description: 'Transform your rooms atmosphere with the Govee RGBIC Floor Lamp Basic. Delivering 1000 lumens of brightness, this sleek black corner lamp features advanced RGBIC technology to display multiple colors simultaneously along a single line. Enjoy customizable dynamic light effects, music sync mode, and effortless hands-free voice control via Alexa and Google Assistant—perfect for gaming setups, living rooms, and bedrooms.',
    image: 'https://m.media-amazon.com/images/I/61SdRNLwZzL._AC_SX342_SY445_QL70_FMwebp_.jpg',
    price: 64.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/02sYYGtj',
  },
  {
    id: 'g5-b',
    page: 'gaming',
    title: 'Airlonv LED Desk Lamp with Clamp, 17" Stepless Dimming Light, Black',
    description: 'Brighten your workspace with the Airlonv LED Desk Lamp with Clamp. Featuring a 17" light bar, stepless dimming, and adjustable color temperatures, this eye-caring desk lamp provides customizable, flicker-free illumination. Its flexible gooseneck and space-saving clamp design easily attach to any desk, making it ideal for studying, working, reading, or crafting.',
    image: 'https://m.media-amazon.com/images/I/71Xa0fzUiGL._AC_SX342_SY445_QL70_FMwebp_.jpg',
    price: 19.99,
    originalPrice: 25.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/08cArnVF',
  },
  {
    id: 'g5',
    page: 'gaming',
    title: 'Govee Uplighter Floor Lamp for Living Room',
    description: 'a 330° rotating lamp head with a dynamic RGBIC water ripple projector, tri-zone lighting control with 1,000lm task lighting',
    image: 'https://m.media-amazon.com/images/I/81bgKHOSSWL._AC_SL1500_.jpg',
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/0aoJSjbE',
  },
  {
    id: 'g6-d',
    page: 'gaming',
    title: 'Cell Phone Stand',
    description: 'Web: Keep your hands free and your phone at the perfect viewing angle with this sturdy, adjustable desk stand for easy video calls and streaming!',
    image: 'https://m.media-amazon.com/images/I/61KD4hoirXL._AC_SL1289_.jpg',
    price: 9.99,
    originalPrice: 17.99,
    rating: 4.5,
    reviews: 71350,
    category: 'Switch Accessories',
    affiliateLink: 'https://a.co/d/09u492Sz',
  },
   {
    id: 'g6-c',
    page: 'gaming',
    title: 'Screen Protector Tempered Glass for Nintendo Switch',
    description: 'Premium tempered glass screen protector for Nintendo Switch offers scratch resistance, high clarity, and effortless bubble-free installation.',
    image: 'https://m.media-amazon.com/images/I/71ccbRRebHL._AC_SX679_.jpg',
    price: 7.99,
    originalPrice: 9.99,
    rating: 4.6,
    reviews: 3467,
    category: 'Switch Accessories',
    affiliateLink: 'https://a.co/d/0e6IBasD',
  },
   {
    id: 'g6-b',
    page: 'gaming',
    title: 'Wireless Switch Controller',
    description: 'Elevate your gaming with this Multi-Platform Wireless Switch Controller, fully compatible with Nintendo Switch, Switch 2, Lite, and OLED models.',
    image: 'https://m.media-amazon.com/images/I/71fQOXATOML._SL1500_.jpg',
    price: 26.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviews: 765,
    category: 'Switch Accessories',
    affiliateLink: 'https://a.co/d/0en1AD1H',
  },
    {
    id: 'g6',
    page: 'gaming',
    title: 'Orzly Carrying Case for Nintendo Switch 2 2025 Console with Screen Padding',
    description: 'Protect your next-gen console on the go with the Orzly Carrying Case designed for the Nintendo Switch 2.',
    image: 'https://m.media-amazon.com/images/I/812xPtswK9L._SL1500_.jpg',
    price: 26.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 765,
    category: 'Switch Accessories',
    affiliateLink: 'https://a.co/d/04pf0H8l',
  },
  {
    id: 'g7',
    page: 'gaming',
    title: 'Dart Board',
    description: 'Bring the arcade home with a professional-grade dartboard that features self-healing fibers, staple-free wiring, and built-in scoring precision for endless game nights!',
    image: 'https://m.media-amazon.com/images/I/91we94LQPhL._AC_SL1500_.jpg',
    price: 25.99,
    originalPrice: 29.99,
    rating: 4.6,
    reviews: 6626,
    category: 'Games',
    affiliateLink: 'https://a.co/d/0ijkvS4E',
  },
  {
    id: 'g8-d',
    page: 'gaming',
    title: 'Samsung T9 Portable SSD 1TB, USB',
    description: 'Speed up your workflow with the lightning-fast Samsung T9 Portable SSD 1TB—delivering read/write speeds up to 2,000 MB/s to transfer massive files and 4K video in seconds!',
    image: 'https://m.media-amazon.com/images/I/71EESd1deTL._AC_SL1500_.jpg',
    price: 239.99,
    originalPrice: 287.99,
    rating: 4.5,
    reviews: 2927,
    category: 'Storage',
    affiliateLink: 'https://a.co/d/05nBijuP',
  },
  {
    id: 'g8-c',
    page: 'gaming',
    title: 'Laptop Lap Desk for Bed, SAIJI X-Large Adjustable Laptop Table',
    description: 'Heavy-duty industrial TV console table and entertainment center features sturdy steel framing, rich wood tones, and generous storage.',
    image: 'https://m.media-amazon.com/images/I/91l4GH8bSDL._AC_SX679_.jpg',
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.8,
    reviews: 2890,
    category: 'Storage',
    affiliateLink: 'https://a.co/d/09rZMnd2',
  },
   {
    id: 'g8-b',
    page: 'gaming',
    title: 'Laptop Lap Desk for Bed, SAIJI X-Large Adjustable Laptop Table',
    description: 'Work or relax in complete comfort with the SAIJI X-Large Adjustable Laptop Lap Desk. Designed for beds, couches.',
    image: 'https://m.media-amazon.com/images/I/71nLTaB-KvL._AC_SL1500_.jpg',
    price: 69.99,
    originalPrice: 89.99,
    rating: 4.8,
    reviews: 2890,
    category: 'Storage',
    affiliateLink: 'https://a.co/d/0eyE9izt',
  },
   {
    id: 'g8',
    page: 'gaming',
    title: 'Seagate Portable 2TB External Hard Drive',
    description: 'offers easy plug-and-play drag-and-drop storage with USB 3.0 connectivity, universal compatibility for PC, Mac,Data Recovery Services.',
    image: 'https://m.media-amazon.com/images/I/61EFaBPAnVL._AC_SL1500_.jpg',
    price: 156.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviews: 2890,
    category: 'Storage',
    affiliateLink: 'https://a.co/d/075RweKX',
  },
  {
    id: 'g9-e',
    page: 'gaming',
    title: 'Computer Desk',
    description: 'Upgrade your workspace with a sturdy, spacious computer desk built for clean cable management, maximum legroom, and effortless productivity.',
    image: 'https://m.media-amazon.com/images/I/712ZBhJ6RkL._AC_SX679_.jpg',
    price: 84.99,
    originalPrice: 109.99,
    rating: 4.6,
    reviews: 2302,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/0gThuOVR',
  },
  {
    id: 'g9-d',
    page: 'gaming',
    title: 'SteelSeries QcK Gaming Mouse Pad',
    description: 'Legendary SteelSeries QcK gaming mouse pad features micro-woven cloth for precise sensor tracking and a non-slip rubber base.',
    image: 'https://m.media-amazon.com/images/I/41sNt1-AT6L._AC_SL1500_.jpg',
    price: 29.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 4362,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/0e2dYaYV',
  },
   {
    id: 'g9-c',
    page: 'gaming',
    title: ' L Shaped Office Desk with Power Outlets and Type-C Port',
    description: 'Maximize your corner space with this 55-Inch L-Shaped Gaming & Office Desk in Rustic Brown. Built for ultimate productivity and organization.',
    image: 'https://m.media-amazon.com/images/I/81dAwnxUDkL._AC_SX679_.jpg',
    price: 109.99,
    originalPrice: 119.99,
    rating: 4.5,
    reviews: 1678,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/09A7MCt2',
  },
  {
    id: 'g9-b',
    page: 'gaming',
    title: 'Japanese Mouse Pad',
    description: 'Upgrade your desk setup with this XL Japanese Anime Mouse Pad (31.5” x 11.8”). Designed to fit both your keyboard and mouse.',
    image: 'https://m.media-amazon.com/images/I/71sIHaXtpOL._AC_SL1500_.jpg',
    price: 14.99,
    originalPrice: 34.99,
    rating: 4.5,
    reviews: 1678,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/0bsUfUhs',
  },
  {
    id: 'g9',
    page: 'gaming',
    title: 'Aothia Leather Office Desk Pad Protector',
    description: 'features a 31.5" x 15.7" waterproof PU leather surface with a non-slip suede backing, serving as a dual desk blotter and writing mouse pad, spills, and daily wear.',
    image: 'https://m.media-amazon.com/images/I/81A14OTXb9L._AC_SX300_SY300_QL70_FMwebp_.jpg',
    price: 13.99,
    originalPrice: 34.99,
    rating: 4.5,
    reviews: 1678,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/02dOO5fP',
  },
  {
    id: 'g10-d',
    page: 'gaming',
    title: ' Wired Gaming Headset',
    description: 'Lock into total audio immersion with clear surround sound, a noise-canceling mic, and ultra-comfortable ear cushions for marathon gaming sessions.',
    image: 'https://m.media-amazon.com/images/I/71AMEEP3HLL._AC_SX679_.jpg',
    price: 74.99,
    originalPrice: 99.99,
    rating: 4.9,
    reviews: 12191,
    category: 'PC Accessories',
    affiliateLink: 'https://a.co/d/03IW6hrT',
  },
   {
    id: 'g10-c',
    page: 'gaming',
    title: 'YOWU Cat Ear Headphones',
    description: 'YOWU cat ear headphones feature customizable RGB lighting, wireless Bluetooth connectivity, and immersive sound for gaming and streaming.',
    image: 'https://m.media-amazon.com/images/I/61ePQsuyT3L._AC_SX679_.jpg',
    price: 159.99,
    originalPrice: 189.99,
    rating: 4.5,
    reviews: 3543,
    category: 'PC Accessories',
    affiliateLink: 'https://a.co/d/0aMaP2gW',
  },
  {
    id: 'g10-b',
    page: 'gaming',
    title: 'llano V12 Gaming Laptop Cooling Pad Laptop Cooler Laptop Cooling Fan Stand',
    description: 'Keep your laptop running at peak performance with the llano V12 Gaming Laptop Cooling Pad. Engineered with high-speed industrial-grade cooPUe wind speeds.',
    image: 'https://m.media-amazon.com/images/I/71t9L9oIYhL._AC_SL1500_.jpg',
    price: 95.99,
    originalPrice: 119.99,
    rating: 4.6,
    reviews: 543,
    category: 'PC Accessories',
    affiliateLink: 'https://a.co/d/0eX1qlpV',
  },
  {
    id: 'g10',
    page: 'gaming',
    title: 'Ultimate 2 Wireless Controller for PC',
    description: 'switchable Hall Effect and tactile triggers, an ultra-low latency 1000Hz polling rate via 8Speed 2.4G wireless, RGB Fire Ring lighting, extra back paddle buttons.',
    image: 'https://m.media-amazon.com/images/I/31DK+auiqfL._SX342_SY445_QL70_FMwebp_.jpg',
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviews: 543,
    category: 'PC Accessories',
    affiliateLink: 'https://a.co/d/0b72MatL',
  },
  {
    id: 'g11-d',
    page: 'gaming',
    title: '3D Wall Panels Diamond',
    description: 'Transform plain, boring walls instantly with these lightweight 3D diamond panels that create a stunning, textured feature wall in any room!  ',
    image: 'https://m.media-amazon.com/images/I/51h-oPgZS8L._SX522_.jpg',
    price: 39.99,
    originalPrice: 69.99,
    rating: 4.6,
    reviews: 2645,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/00nqFEzT',
  },
   {
    id: 'g11-c',
    page: 'gaming',
    title: 'BENGOO G9000 Stereo Gaming Headset',
    description: 'Immerse yourself in every game with the BENGOO G9000 Stereo Gaming Headset. Equipped with 7.1 surround sound drivers, a noise-isolating omnidirectional microphone, and comfortable soft memory earmuffs, this multi-platform headset delivers crystal-clear audio and all-day comfort. Features built-in LED lighting and 3.5mm jack compatibility for PS5, PS4, Xbox Series X|S, Xbox One, PC, and Nintendo Switch.',
    image: 'https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SL1000_.jpg',
    price: 19.99,
    originalPrice: 29.99,
    rating: 4.4,
    reviews: 432,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/0a5aIiC4',
  },
  {
    id: 'g11-b',
    page: 'gaming',
    title: 'YEEBAY Target Shooting Toys',
    description: 'Bring active, safe fun to playtime with the YEEBAY Target Shooting Toys Set. Designed for kids ages 6 and up, this high-energy game includes a standing scoring target board, foam ball air guns, and soft, lightweight foam balls for safe indoor or outdoor play. Perfect for improving hand-eye coordination, active family fun, and friendly competition.',
    image: 'https://m.media-amazon.com/images/I/71psM3gJHSL._AC_SX679_.jpg',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 432,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/0asR2GnX',
  },
  {
    id: 'g11',
    page: 'gaming',
    title: 'LEGO Super Mario Game Boy',
    description: 'a 421-piece, near 1:1 scale collectible model kit for adults featuring interactive buttons, interchangeable Game Paks, lenticular game screens, and a buildable display stand.',
    image: 'https://m.media-amazon.com/images/I/71AV0wHyDUL._AC_SX679_.jpg',
    price: 59.99,
    originalPrice: 68.99,
    rating: 4.4,
    reviews: 432,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/06bKd4xz',
  },
  {
    id: 'g12-d',
    page: 'gaming',
    title: 'Magnetic Wooden Chess',
    description: 'Play chess anywhere without losing a single piece with this handcrafted magnetic wooden set, featuring sleek folding storage for effortless travel.',
    image: 'https://m.media-amazon.com/images/I/713asLPZglL._AC_SL1500_.jpg',
    price: 39.99,
    originalPrice: 52.99,
    rating: 4.8,
    reviews: 2806,
    category: 'Merchandise',
    affiliateLink: 'https://a.co/d/010F9qFQ',
  },
  {
    id: 'g12-c',
    page: 'gaming',
    title: 'Cooling Station with LED Controller Charging Station for PlayStation',
    description: 'Immerse yourself in every game with the BENGOO G9000 Stereo Gaming Headset. Equipped with 7.1 surround sound drivers, a noise-isolating omnidirectional microphone.',
    image: 'https://m.media-amazon.com/images/I/713asLPZglL._AC_SL1500_.jpg',
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.5,
    reviews: 621,
    category: 'Merchandise',
    affiliateLink: 'https://a.co/d/09FcyMTu',
  },
  {
    id: 'g12-b',
    page: 'gaming',
    title: 'Cooling Station with LED Controller Charging Station for PlayStation',
    description: 'Immerse yourself in every game with the BENGOO G9000 Stereo Gaming Headset. Equipped with 7.1 surround sound drivers, a noise-isolating omnidirectional microphone.',
    image: 'https://m.media-amazon.com/images/I/713asLPZglL._AC_SL1500_.jpg',
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.5,
    reviews: 621,
    category: 'Merchandise',
    affiliateLink: 'https://a.co/d/09FcyMTu',
  },
  {
    id: 'g12',
    page: 'gaming',
    title: 'Funko POP! Games: Pokemon ',
    description: 'an officially licensed vinyl figurine standing approximately 5.15 inches tall, perfect for shelf display or as a collectible for Pokémon fans.',
    image: 'https://m.media-amazon.com/images/I/71HjHpzxdIL._AC_SL1500_.jpg',
    price: 15.99,
    originalPrice: 24.99,
    rating: 4.5,
    reviews: 621,
    category: 'Merchandise',
    affiliateLink: 'https://a.co/d/0iaDIklu',
  },
  
  // ===== FITNESS PRODUCTS =====
  {
    id: 'fi1-d',
    page: 'fitness',
    title: 'Classic Wrist Straps',
    description: 'Maximize your lifting power and eliminate grip fatigue with classic heavy-duty wrist straps, built for heavy deadlifts, rows, and pull-days.',
    image: 'https://m.media-amazon.com/images/I/91lMg3Y94JL._AC_SX679_.jpg',
    price: 49.99,
    originalPrice: 59.99,
    rating: 4.7,
    reviews: 2027,
    category: 'Weights',
    affiliateLink: 'https://a.co/d/07AoeG4z',
    featured: true,
  },
  {
    id: 'fi1-c',
    page: 'fitness',
    title: 'Amazon Basics Neoprene Dumbbell Hand Weights for Exercise and Muscle Toning',
    description: 'Enhance your strength training routine with Amazon Basics Neoprene Dumbbell Hand Weights. Featuring a non-slip neoprene coating for a secure grip and a hexagonal shape to prevent rolling, these durable dumbbells are ideal for muscle toning, cardio workouts, and home exercise routines.',
    image: 'https://m.media-amazon.com/images/I/61Ba8KTFtgL._AC_SL1500_.jpg',
    price: 36.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviews: 2104,
    category: 'Weights',
    affiliateLink: 'https://a.co/d/08vr63EI',
    featured: true,
  },
  {
    id: 'fi1-b',
    page: 'fitness',
    title: 'MERACH Exercise Bike, Magnetic Friction Stationary Bike for Home',
    description: 'Achieve your fitness goals at home with the MERACH Magnetic Stationary Exercise Bike. Designed for a smooth, whisper-quiet ride, it features adjustable magnetic resistance, a heavy-duty steel frame, and an ergonomic padded seat for maximum comfort. Complete with a digital monitor to track your workout metrics and an integrated device holder, its the perfect compact solution for low-impact cardio workouts.',
    image: 'https://m.media-amazon.com/images/I/71l+KL4uazL._AC_SX679_.jpg',
    price: 269.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 2104,
    category: 'Weights',
    affiliateLink: 'https://a.co/d/0hcCjGbr',
    featured: true,
  },
  {
    id: 'fi1',
    page: 'fitness',
    title: 'Zeerun Weighted Vest',
    description: 'made from skin-friendly, leak-proof neoprene with double-stitched seams, thick shoulder padding, adjustable front buckles, and safety reflective stripes for walking, rucking, and strength training.',
    image: 'https://m.media-amazon.com/images/I/81zh-RIi18L._AC_SL1500_.jpg',
    price: 14.99,
    originalPrice: 35.99,
    rating: 4.8,
    reviews: 2104,
    category: 'Weights',
    affiliateLink: 'https://a.co/d/0hfVbnh5',
    featured: true,
  },

  {
    id: 'fi2-d',
    page: 'fitness',
    title: 'Zero Sugar Powder',
    description: 'Enjoy guilt-free sweetness with zero-sugar powder—the perfect zero-calorie substitute for baking, daily coffee, and cold drinks without any bitter aftertaste!',
    image: 'https://m.media-amazon.com/images/I/71Dp+t3ZYpL._AC_SL1500_.jpg',
    price: 27.99,
    originalPrice: 29.99,
    rating: 4.8,
    reviews: 10440,
    category: 'Supplements',
    affiliateLink: 'https://a.co/d/0fjPpk8f',
    featured: true,
  },
   {
    id: 'fi2-c',
    page: 'fitness',
    title: 'Nutricost Creatine Monohydrate Powder',
    description: 'Power your strength and athletic performance with Nutricost Creatine Monohydrate Powder in Shaqs Berry Blast flavor. Delivering pure, high-quality micronized creatine monohydrate with a delicious berry taste, this 500-gram tub supports muscle growth, endurance, and faster recovery.',
    image: 'https://m.media-amazon.com/images/I/71cU1RChrcL._AC_SL1500_.jpg',
    price: 23.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 5730,
    category: 'Supplements',
    affiliateLink: 'https://a.co/d/0gsihDf1',
    featured: true,
  },
   {
    id: 'fi2-b',
    page: 'fitness',
    title: 'Jocko Mölk 30g Grass Fed Protein Shakes',
    description: 'Fuel your body with Jocko Mölk Ready-to-Drink Chocolate Protein Shakes. Packed with 30g of grass-fed protein, zero added sugar, and low net carbs, this keto-friendly shake delivers a smooth, delicious chocolate taste without artificial sweeteners. Perfectly formulated for muscle recovery, clean energy, and convenient on-the-go nutrition in a ready-to-drink 12 fl oz pack.',
    image: 'https://m.media-amazon.com/images/I/81dUI1WWhQL._SX679_.jpg',
    price: 44.99,
    originalPrice: 69.99,
    rating: 4.7,
    reviews: 5430,
    category: 'Supplements',
    affiliateLink: 'https://a.co/d/00rYUxdC',
    featured: true,
  },
  {
    id: 'fi2',
    page: 'fitness',
    title: 'Protein Shaker Bottle for Protein Mixes',
    description: 'a 100% leak-proof design, six wire whisks for clump-free mixing, stackable BPA-free plastic construction, and dishwasher-safe convenience in an Earth Tones color collection.',
    image: 'https://m.media-amazon.com/images/I/812Aa6MATwL._AC_SY879_.jpg',
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.7,
    reviews: 5430,
    category: 'Supplements',
    affiliateLink: 'https://a.co/d/0bd7myWd',
    featured: true,
  },
  {
    id: 'fi3-d',
    page: 'fitness',
    title: 'Dumbbells Set Used as Barbell',
    description: 'Switch seamlessly between dumbbells and a full barbell using this versatile, space-saving set—perfect for total-body strength training at home!',
    image: 'https://m.media-amazon.com/images/I/71BE37ZZfLL._AC_SX679_.jpg',
    price: 76.99,
    originalPrice: 89.99,
    rating: 4.8,
    reviews: 5005,
    category: 'Travel',
    affiliateLink: 'https://a.co/d/0iDFs8ds',
  },
  {
    id: 'fi3-c',
    page: 'fitness',
    title: 'One Home Gym System',
    description: 'Build maximum strength and target every major muscle group with the All-In-One Home Gym System. Engineered with a heavy-duty steel frame, smooth high and low cable pulleys, and an adjustable weight stack, this comprehensive workout station delivers gym-quality resistance in a compact footprint. Perform chest presses, lat pulldowns, leg extensions, and core exercises safely at home without needing multiple bulky machines.  ',
    image: 'https://m.media-amazon.com/images/I/81cEHK-vWoL._AC_SX679_.jpg',
    price: 144.99,
    originalPrice: 189.99,
    rating: 4.6,
    reviews: 1482,
    category: 'Travel',
    affiliateLink: 'https://a.co/d/0imqiGzO',
  },
  {
    id: 'fi3-b',
    page: 'fitness',
    title: 'TRX GO Suspension Trainer',
    description: 'Achieve a full-body workout anywhere with the TRX GO Suspension Trainer. Lightweight, portable, and easy to set up in seconds, this bodyweight training system lets you burn fat, build lean muscle, and strengthen your core using your own body weight. Comes complete with indoor/outdoor anchors and a travel pouch—perfect for home workouts, travel, or training on the go.',
    image: 'https://m.media-amazon.com/images/I/71fWIMZHGeL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 111.99,
    originalPrice: 139.99,
    rating: 4.6,
    reviews: 1432,
    category: 'Travel',
    affiliateLink: 'https://a.co/d/08w4Gzca',
  },
  {
    id: 'fi3',
    page: 'fitness',
    title: 'VINSGUIR Ab Roller Wheel',
    description: 'a 3.2-inch ultra-wide dual wheel with non-slip EVA rubber cotton handles, a high-strength stainless steel shaft supporting up to 440 lbs, and an included knee pad for extra comfort during core strength workouts.',
    image: 'https://m.media-amazon.com/images/I/71CH7yY6m2L._AC_SX679_.jpg',
    price: 23.99,
    originalPrice: 29.99,
    rating: 4.6,
    reviews: 1432,
    category: 'Travel',
    affiliateLink: 'https://a.co/d/0198ptTE',
  },
  {
    id: 'fi4-d',
    page: 'fitness',
    title: 'Waver Vibration Plate Exercise Machine',
    description: 'Boost your home workouts with the Waver Vibration Plate—designed to stimulate full-body muscle contractions, improve circulation, and speed up recovery in just minutes a day!',
    image: 'https://m.media-amazon.com/images/I/71VaXGNl5pL._SX522_.jpg',
    price: 199.99,
    originalPrice: 269.99,
    rating: 4.8,
    reviews: 30548,
    category: 'Machines',
    affiliateLink: 'https://a.co/d/0fy8Lqaq',
  },
  {
    id: 'fi4-c',
    page: 'fitness',
    title: 'MERACH Exercise Bike, Magnetic Friction Stationary Bike with Brake Pad',
    description: 'Upgrade your home cardio workouts with the MERACH Magnetic Friction Exercise Bike. Featuring a quiet magnetic resistance system with a quick-stop brake pad.',
    image: 'https://m.media-amazon.com/images/I/71l+KL4uazL._AC_SX679_.jpg',
    price: 269.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 8676,
    category: 'Machines',
    affiliateLink: 'https://a.co/d/08CNPQHw',
  },
  {
    id: 'fi4-b',
    page: 'fitness',
    title: 'Lifepro Waver Vibration Plate Exercise Machine with 99 Speeds & 10 Presets',
    description: 'Enhance your workouts and accelerate recovery with the Lifepro Waver Vibration Plate Exercise Machine. Designed to stimulate muscles',
    image: 'https://m.media-amazon.com/images/I/71VaXGNl5pL._SX522_.jpg',
    price: 199.99,
    originalPrice: 229.99,
    rating: 4.5,
    reviews: 876,
    category: 'Machines',
    affiliateLink: 'https://a.co/d/0bDkaQ8a',
  },
  {
    id: 'fi4',
    page: 'fitness',
    title: 'Vibration Plate Fitness Platform Exercise Machine Body',
    description: 'Compact folding treadmill with 3HP motor, 12 programs, and Bluetooth app sync.',
    image: 'https://m.media-amazon.com/images/I/71q91XoN2IL._AC_SX679_.jpg',
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviews: 876,
    category: 'Machines',
    affiliateLink: 'https://a.co/d/07loBarI',
  },
 {
    id: 'fi5-d',
    page: 'fitness',
    title: 'AMAZTIM Smart Watch, Rugged Fitness Watch, 5 ATM & IP69K, 1.43" AMOLED',
    description: 'Conquer tough environments with the AMAZTIM Rugged Smartwatch, engineered with 5 ATM & IP69K military-grade water and dust resistance.',
    image: 'https://m.media-amazon.com/images/I/612juLR95TL._AC_SX679_.jpg',
    price: 499.99,
    originalPrice: 549.99,
    rating: 4.5,
    reviews: 1597,
    category: 'Tracking Device',
    affiliateLink: 'https://a.co/d/07Gogw14',
  },
  {
    id: 'fi5-c',
    page: 'fitness',
    title: 'AMAZTIM Smart Watch, Rugged Fitness Watch, 5 ATM & IP69K, 1.43" AMOLED',
    description: 'Conquer tough environments with the AMAZTIM Rugged Smartwatch, engineered with 5 ATM & IP69K military-grade water and dust resistance.',
    image: 'https://m.media-amazon.com/images/I/71vlhnALmQL._AC_SL1500_.jpg',
    price: 129.99,
    originalPrice: 169.99,
    rating: 4.5,
    reviews: 2654,
    category: 'Tracking Device',
    affiliateLink: 'https://a.co/d/08aNjsc1',
  },
  {
    id: 'fi5-b',
    page: 'fitness',
    title: 'Garmin vívoactive® 6, Health & Fitness GPS Smartwatch, 42mm, Slate',
    description: 'Track your wellness and elevate your active lifestyle with the Garmin vívoactive® 6 Health & Fitness GPS Smartwatch (42mm, Slate) .  ',
    image: 'https://m.media-amazon.com/images/I/611jnYHa1OL._AC_SL1500_.jpg',
    price: 299.99,
    originalPrice: 339.99,
    rating: 4.5,
    reviews: 2654,
    category: 'Tracking Device',
    affiliateLink: 'https://a.co/d/0fNBMPN6',
  },
   {
    id: 'fi5',
    page: 'fitness',
    title: 'Google Fitbit Air Special Edition Stephen Curry - Screenless Tracker',
    description: 'a distraction-free screenless design, 24/7 heart rate and sleep tracking, a sweatproof water-resistant coating, personalized AI-powered coaching via Google Health Premium.',
    image: 'https://m.media-amazon.com/images/I/71FS8LWK7QL._AC_SX679_.jpg',
    price: 129.99,
    originalPrice: 139.99,
    rating: 4.5,
    reviews: 2654,
    category: 'Tracking Device',
    affiliateLink: 'https://a.co/d/01RzlUMI',
  },
  {
    id: 'fi6-d',
    page: 'fitness',
    title: 'Water Bottle',
    description: 'Stay hydrated all day long with this durable, leak-proof water bottle—designed to keep your drinks icy cold for hours with a convenient, eco-friendly design!',
    image: 'https://m.media-amazon.com/images/I/71v93FDfRoL._AC_SL1500_.jpg',
    price: 28.00,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 28739,
    category: 'Water Bottles',
    affiliateLink: 'https://a.co/d/03v2QWWo',
  },
   {
    id: 'fi6-c',
    page: 'fitness',
    title: 'FineDine Insulated Water Bottles with Straw',
    description: 'Stay hydrated on the go with FineDine Insulated Water Bottles with Straw lid. Built with double-wall stainless steel to keep drinks icy cold for hours.',
    image: 'https://m.media-amazon.com/images/I/91vVZHoDpKL._AC_SL1500_.jpg',
    price: 28.00,
    originalPrice: 39.99,
    rating: 4.7,
    reviews: 4321,
    category: 'Water Bottles',
    affiliateLink: 'https://a.co/d/04Iz8PYO',
  },
  {
    id: 'fi6-b',
    page: 'fitness',
    title: 'HydroJug Traveler 40oz, Insulated Tumbler with Handle & Straw, Cream',
    description: 'Stay hydrated in style with the HydroJug Traveler 40oz Insulated Tumbler in Cream. Featuring double-wall stainless steel insulation.',
    image: 'https://m.media-amazon.com/images/I/51rnEI9emNL._AC_SX679_.jpg',
    price: 31.00,
    originalPrice: 59.99,
    rating: 4.7,
    reviews: 4321,
    category: 'Water Bottles',
    affiliateLink: 'https://a.co/d/0ik3s3Pg',
  },
  {
    id: 'fi6',
    page: 'fitness',
    title: 'RAYMYLO One Gallon Water Bottle Insulated',
    description: 'features 128 oz triple-walled vacuum stainless steel insulation that keeps drinks cold up to 48 hours, leak-proof straw and spout lids.',
    image: 'https://m.media-amazon.com/images/I/71IL2cwmmqL._AC_SL1500_.jpg',
    price: 44.98,
    originalPrice: 59.99,
    rating: 4.7,
    reviews: 4321,
    category: 'Water Bottles',
    affiliateLink: 'https://a.co/d/034vp6XJ',
  },
  {
    id: 'fi7-d',
    page: 'fitness',
    title: 'Gymreapers Knee Sleeves',
    description: 'Protect your knees and lift heavier with confidence using Gymreapers Knee Sleeves—designed to deliver maximum compression, joint stability, and warm support during heavy squats and leg days!',
    image: 'https://m.media-amazon.com/images/I/717Q-K9Uk+L._SX522_.jpg',
    price: 59.99,
    originalPrice: 98.99,
    rating: 4.6,
    reviews: 1735,
    category: 'CrossFit',
    affiliateLink: 'https://a.co/d/0eK9emMb',
  },
  {
    id: 'fi7-c',
    page: 'fitness',
    title: 'High Performance Elbow Sleeve Support for Weightlifting',
    description: 'Enhance your lifting performance and protect your joints with these High Performance Elbow Support Sleeves.',
    image: 'https://m.media-amazon.com/images/I/613+E97xPWL._AC_SX679_.jpg',
    price: 49.99,
    originalPrice: 104.99,
    rating: 4.6,
    reviews: 1735,
    category: 'CrossFit',
    affiliateLink: 'https://a.co/d/03bTD0UO',
  },
   {
    id: 'fi7-b',
    page: 'fitness',
    title: 'Ally Peaks Pull Up Bar for Doorway',
    description: 'Transform any doorway into a personal home gym with the Ally Peaks Pull-Up Bar.',
    image: 'https://m.media-amazon.com/images/I/61Ai3fZLi9L._AC_SL1500_.jpg',
    price: 28.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 765,
    category: 'CrossFit',
    affiliateLink: 'https://a.co/d/0ekuijMC',
  },
  {
    id: 'fi7',
    page: 'fitness',
    title: 'Push Up Board',
    description: 'a durable ABS construction supporting up to 300 kg (660 lbs), non-slip silicone handles with built-in storage, and a portable folding design.',
    image: 'https://m.media-amazon.com/images/I/71PEbWkLmoL._AC_SL1500_.jpg',
    price: 31.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 765,
    category: 'CrossFit',
    affiliateLink: 'https://a.co/d/0fu7eO4e',
  },
  {
    id: 'fi8-d',
    page: 'fitness',
    title: 'Pilates Circle',
    description: 'Maximize core stability and protect your lower back with the Element 26 Self-Locking Weight Lifting Belt.',
    image: 'https://m.media-amazon.com/images/I/81Pr4xXr3QL._AC_SX679_.jpg',
    price: 21.99,
    originalPrice: 23.99,
    rating: 4.6,
    reviews: 9793,
    category: 'Home Workout',
    affiliateLink: 'https://a.co/d/04XpFqFt',
  },
   {
    id: 'fi8-c',
    page: 'fitness',
    title: 'Element 26 Self-Locking Weight Lifting Belt',
    description: 'Maximize core stability and protect your lower back with the Element 26 Self-Locking Weight Lifting Belt.',
    image: 'https://m.media-amazon.com/images/I/71q1Yl9qZ4L._AC_SX679_.jpg',
    price: 34.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 1876,
    category: 'Home Workout',
    affiliateLink: 'https://a.co/d/0gvTZmtN',
  },
  {
    id: 'fi8-b',
    page: 'fitness',
    title: 'Jump Rope',
    description: 'Achieve your fitness and cardio goals with this Tangle-Free Rapid Speed Jump Rope. Featuring high-speed 360° ball bearings for smooth.',
    image: 'https://m.media-amazon.com/images/I/71wm42EtoNL._AC_SX679_.jpg',
    price: 8.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviews: 1876,
    category: 'Home Workout',
    affiliateLink: 'https://a.co/d/0bbUH3Di',
  },
  {
    id: 'fi8',
    page: 'fitness',
    title: 'FLYBIRD WB5 Weight Bench',
    description: 'The FLYBIRD WB5 Weight Bench is an ASTM-certified, 800 lb heavy-duty workout bench featuring a 30-inch extended backrest.',
    image: 'https://m.media-amazon.com/images/I/71ijsNeaN-L._AC_SL1500_.jpg',
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviews: 1876,
    category: 'Home Workout',
    affiliateLink: 'https://a.co/d/06gcSAsx',
  },
  {
    id: 'fi9-c',
    page: 'fitness',
    title: 'Sauna Shirt for Men',
    description: 'Trap body heat, increase sweat, and burn extra calories during every workout with this high-compression Sauna Shirt for Men—designed to speed up warmups and maximize water weight loss!',
    image: 'https://m.media-amazon.com/images/I/81vp8TiA5JL._AC_SY879_.jpg',
    price: 26.99,
    originalPrice: 49.99,
    rating: 4.7,
    reviews: 12586,
    category: 'Outdoor',
    affiliateLink: 'https://a.co/d/06HlRjLA',
  },
  {
    id: 'fi9-b',
    page: 'fitness',
    title: 'SUPERJARE 0.56 Thick 96 Sq Ft Rubber Top Gym Flooring for Home Gym',
    description: 'Upgrade your home gym floor with SUPERJARE 0.56" Thick Rubber Top Interlocking Tiles, offering 96 sq ft of heavy-duty coverage.',
    image: 'https://m.media-amazon.com/images/I/81Hv7+S4MeL._AC_SL1500_.jpg',
    price: 189.99,
    originalPrice: 249.99,
    rating: 4.6,
    reviews: 458,
    category: 'Outdoor',
    affiliateLink: 'https://a.co/d/06HlRjLA',
  },
  {
    id: 'fi9',
    page: 'fitness',
    title: 'NICEPEOPLE Adjustable Weight Bench for Home Gym',
    description: 'a 660 lb capacity alloy steel frame with 8 adjustable backrest angles, high-density sweat-resistant leather padding, 4 rotatable leveling foot caps.',
    image: 'https://m.media-amazon.com/images/I/719zG2ZrQzL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 62.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 1098,
    category: 'Outdoor',
    affiliateLink: 'https://a.co/d/0eegAVtJ',
  },
  {
    id: 'fi10-c',
    page: 'fitness',
    title: 'Lifting Wrist Straps for Weightlifting',
    description: 'Eliminate grip fatigue and target muscle growth with heavy-duty weightlifting wrist straps—engineered for maximum grip support during heavy deadlifts, shrugs, and barbell rows.',
    image: 'https://m.media-amazon.com/images/I/61aGurYmorL._AC_SX679_.jpg',
    price: 14.99,
    originalPrice: 27.99,
    rating: 4.7,
    reviews: 1342,
    category: 'Strength',
    affiliateLink: 'https://a.co/d/0fAxLetK',
  },
  {
    id: 'fi10-b',
    page: 'fitness',
    title: 'FitBeast-Grip Strengthener-Forearm Strengthener-Hand Grips Strengthener Kit',
    description: 'Level up your hand, wrist, and forearm power with the FitBeast 5-Pack Hand Grip Strengthener Kit. Featuring an adjustable resistance hand gripper.',
    image: 'https://m.media-amazon.com/images/I/718tBdzFF6L._AC_SL1500_.jpg',
    price: 16.99,
    originalPrice: 27.99,
    rating: 4.4,
    reviews: 1342,
    category: 'Strength',
    affiliateLink: 'https://a.co/d/070rDQ5I',
  },
  {
    id: 'fi10',
    page: 'fitness',
    title: 'Under Desk Elliptical Machine',
    description: '12 adjustable manual speed levels and automatic modes (P1-P3), forward and reverse pedal motion, ultra-quiet sound-dampening technology.',
    image: 'https://m.media-amazon.com/images/I/71XJsK7LnIL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 84.99,
    originalPrice: 99.99,
    rating: 4.4,
    reviews: 1342,
    category: 'Strength',
    affiliateLink: 'https://a.co/d/0h175f7j',
  },
  {
    id: 'fi11-c',
    page: 'fitness',
    title: 'Health & Fitness Multi-Function Roman Chair',
    description: 'Sculpt your core and strengthen your lower back with this Multi-Function Roman Chair—perfect for targeted back extensions, hyperextensions, decline crunches, and dip training at home!',
    image:'https://m.media-amazon.com/images/I/71SyWINJSZL._AC_SX679_.jpg',
    price: 84.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviews: 6686,
    category: 'Compact',
    affiliateLink: 'https://a.co/d/0hhmALF7',
  },
  {
    id: 'fi11-b',
    page: 'fitness',
    title: 'YOLEO Adjustable Weight Bench',
    description: 'The YOLEO Adjustable Weight Bench features an ASTM-certified 827 lb capacity heavy-duty alloy steel frame, 84 adjustable angle combinations.',
    
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviews: 2374,
    category: 'Compact',
    affiliateLink: 'https://a.co/d/0anX4y2L',
  },
  {
    id: 'fi11',
    page: 'fitness',
    title: 'YOLEO Adjustable Weight Bench',
    description: 'The YOLEO Adjustable Weight Bench features an ASTM-certified 827 lb capacity heavy-duty alloy steel frame, 84 adjustable angle combinations.',
    image: 'https://m.media-amazon.com/images/I/81pu4FK5uSL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 79.99,
    originalPrice: 89.99,
    rating: 4.5,
    reviews: 987,
    category: 'Compact',
    affiliateLink: 'https://a.co/d/0cJ4WCh3',
  },
];

let currentPageId = 'fashion';
let currentCategory = 'All';
let searchQuery = '';

const heroTitleEl = document.getElementById('heroTitle');
const heroDescriptionEl = document.getElementById('heroDescription');
const heroTaglineEl = document.getElementById('heroTagline');
const categoryPillsEl = document.getElementById('categoryPills');
const productGridEl = document.getElementById('productGrid');
const productsCountEl = document.getElementById('productsCount');
const searchInputEl = document.getElementById('searchInput');
const noResultsEl = document.getElementById('noResults');
const navBtns = document.querySelectorAll('.nav-btn');

function init() {
  setupEventListeners();
  renderPage(currentPageId);
}

function setupEventListeners() {
  navBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      navBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      currentPageId = btn.getAttribute('data-page');
      currentCategory = 'All';
      searchQuery = '';
      searchInputEl.value = '';
      renderPage(currentPageId);
    });
  });

  searchInputEl.addEventListener('input', (e) => {
    searchQuery = e.target.value.toLowerCase().trim();
    renderProducts();
  });
}

function renderPage(pageId) {
  const pageData = PAGES.find(p => p.id === pageId);
  if (!pageData) return;

  heroTaglineEl.innerHTML = `<i class="fa-solid fa-circle-check"></i> ${pageData.tagline}`;
  heroTitleEl.innerHTML = `${pageData.heroTitle} <span class="highlight">${pageData.heroHighlight}</span>`;
  heroDescriptionEl.textContent = pageData.heroDescription;

  renderCategories(pageData.categories);
  renderProducts();
}

function renderCategories(categories) {
  categoryPillsEl.innerHTML = '';
  categories.forEach(cat => {
    const pill = document.createElement('button');
    pill.className = `category-pill ${cat === currentCategory ? 'active' : ''}`;
    pill.textContent = cat;
    pill.addEventListener('click', () => {
      document.querySelectorAll('.category-pill').forEach(p => p.classList.remove('active'));
      pill.classList.add('active');
      currentCategory = cat;
      renderProducts();
    });
    categoryPillsEl.appendChild(pill);
  });
}

function renderProducts() {
  const filtered = PRODUCTS.filter(p => {
    const matchesPage = p.page === currentPageId;
    const matchesCategory = currentCategory === 'All' || p.category === currentCategory;
    const matchesSearch = searchQuery === '' || 
      p.title.toLowerCase().includes(searchQuery) || 
      p.description.toLowerCase().includes(searchQuery) ||
      p.category.toLowerCase().includes(searchQuery);

    return matchesPage && matchesCategory && matchesSearch;
  });

  productsCountEl.textContent = `Showing ${filtered.length} products`;

  if (filtered.length === 0) {
    productGridEl.innerHTML = '';
    noResultsEl.classList.remove('hidden');
    return;
  }

  noResultsEl.classList.add('hidden');
  
  productGridEl.innerHTML = filtered.map(product => `
    <div class="product-card">
      <div class="card-image-wrap">
        <img src="${product.image}" alt="${product.title}" class="card-image" loading="lazy">
        ${product.featured ? '<span class="badge-featured">Featured</span>' : ''}
      </div>
      <div class="card-body">
        <span class="card-category">${product.category}</span>
        <h3 class="card-title">${product.title}</h3>
        <p class="card-description">${product.description}</p>
        
        <div class="card-rating">
          <span class="stars"><i class="fa-solid fa-star"></i> ${product.rating}</span>
          <span class="reviews-count">(${product.reviews} reviews)</span>
        </div>

        <div class="card-footer">
          <div class="price-box">
            <span class="current-price">$${product.price.toFixed(2)}</span>
            ${product.originalPrice ? `<span class="original-price">$${product.originalPrice.toFixed(2)}</span>` : ''}
          </div>
          <a href="${product.affiliateLink}" target="_blank" rel="noopener noreferrer" class="cta-button">
            Check on Amazon <i class="fa-solid fa-arrow-up-right-from-square"></i>
          </a>
        </div>
      </div>
    </div>
  `).join('');
}

document.addEventListener('DOMContentLoaded', init);