// PAGES METADATA
const PAGES = [
  {
    id: 'fashion',
    name: 'Fashion & Lifestyle',
    tagline: 'Style for everyone',
    heroTitle: 'Elevate your everyday',
    heroHighlight: 'style',
    heroDescription: 'From everyday essentials to statement pieces — discover top-rated picks across fashion, beauty, and home decor.',
    categories: ['All', 'Women Undergarments', 'Women Makeup', 'Skin Care', 'Women Dresses', 'Men Dresses', 'Hair Products', 'Home Decoration']
  },
  {
    id: 'tech',
    name: 'Tech Products',
    tagline: 'Smart living, simplified',
    heroTitle: 'The latest tech',
    heroHighlight: 'worth buying',
    heroDescription: 'Handpicked gadgets, kitchen tech, and accessories that make everyday life smoother and smarter.',
    categories: ['All', 'Tech Gadgets', 'Kitchen Accessories', 'Room Accessories', 'Tech Tools', 'Mobile & Desktop', 'Speakers', 'Bluetooth Devices']
  },
  {
    id: 'gaming',
    name: 'Gaming Products',
    tagline: 'Level up your setup',
    heroTitle: 'Build your dream',
    heroHighlight: 'gaming setup',
    heroDescription: 'Everything from pro-grade peripherals to ambient lighting — curated for gamers who want the best.',
    categories: ['All', 'Mouse', 'Storage', 'Laptop', 'Xbox Accessories', 'Desk Pads', 'PC Accessories', 'Chair', 'Monitors', 'Merchandise', 'Collectables', 'Room Light', 'Router', 'Switch Accessories']
  },
  {
    id: 'fitness',
    name: 'Fitness Products',
    tagline: 'Train harder, recover smarter',
    heroTitle: 'Gear that moves',
    heroHighlight: 'with you',
    heroDescription: 'Weights, wearables, supplements, and outdoor gear — everything you need to hit your goals.',
    categories: ['All', 'Weights', 'Travel', 'Machines', 'Compact', 'Supplements', 'Tracking Device', 'Outdoor', 'Accessories', 'Flexible Training', 'Water Bottles', 'Strength', 'Home Workout', 'CrossFit', 'Wearable', 'Equipment']
  }
];

// SAMPLE PRODUCTS
const PRODUCTS = [
 {
    id: 'f1-c',
    page: 'fashion',
    title: 'Cosmetics Nose Large Hydrocolloid Pore Strips',
    description: 'Mighty Patch Hero Cosmetics Nose Large Hydrocolloid Pore Strips, 10 Ct | Pimple Patches for Overnight, Dermatologist Approved, Pimple Stickers',
    image: 'https://m.media-amazon.com/images/I/71A2Iw8Eh7L._SX679_.jpg',
    price: 13.99,
    originalPrice: 29.99,
    rating: 4.5,
    reviews:  14732,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/08Y9ONr0',
    featured: true,
  },
  {
    id: 'f1-b',
    page: 'fashion',
    title: 'LivDry Adult XXL Incontinence Underwear',
    description: 'Features a super-absorbent gel core capable of holding up to 50.5 oz (approx. 1,492 mL) of fluid. It quickly locks away moisture to keep skin dry and helps reduce odor.',
    image: 'https://m.media-amazon.com/images/I/71K5vwfHncL._AC_SX679_.jpg',
    price: 77.99,
    originalPrice: 99.55,
    rating: 4.6,
    reviews: 10811,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/0ebTBivX',
    featured: true,
  },
  {
    id: 'f1',
    page: 'fashion',
    title: 'Amazon Essentials Womens Cotton Spandex Bikini Brief Underwear (Available in Plus Size)',
    description: 'FIT: Bikini style panties sit at the low hip with full back coverage COTTON SPANDEX: Soft, smooth cotton blend. This breathable lightweight natural fabric feels soft against your skin, while the added spandex offers a flexible fit that moves with you',
    image: 'https://m.media-amazon.com/images/I/81ERB4kK5gL._AC_SY879_.jpg',
    price: 11.99,
    originalPrice: 24.55,
    rating: 4.6,
    reviews: 10811,
    category: 'Women Undergarments',
    affiliateLink: 'https://a.co/d/0gUH4r5w',
    featured: true,
  },
  {
    id: 'f2-c',
    page: 'fashion',
    title: 'First Aid Beauty Ultra Repair Cream',
    description: 'First Aid Beauty Ultra Repair Cream is an ultra-rich, fragrance-free face and body moisturizer containing 0.5% Colloidal Oatmeal. Designed for sensitive or severely dry skin, it hydrates for up to 24 hours and helps soothe irritation caused by eczema, psoriasis, and rosacea while repairing the skin barrier.',
    image: 'https://m.media-amazon.com/images/I/71eLojzJ+EL._SX522_.jpg',
    price: 35.00,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 5402,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/09xUoIPo',
  },
    {
    id: 'f2-b',
    page: 'fashion',
    title: 'SimplyVital Face Moisturizer Retinol Collagen Hyaluronic Acid Cream 1.7 oz ',
    description: 'Achieve smooth, hydrated, and visibly firm skin day and night. Its lightweight, silky formula deeply moisturizes without feeling heavy. Perfect for face and neck care!',
    image: 'https://m.media-amazon.com/images/I/51dYkEzrtDL._SY300_SX300_QL70_FMwebp_.jpg',
    price: 23.00,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 36402,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/05sxr7fl',
  },
    {
    id: 'f2',
    page: 'fashion',
    title: 'Revision Skincare D·E·J Eye Cream',
    description: 'an advanced, comprehensive eye treatment designed to firm, lift, and smooth the total eye area by targeting the dermal-epidermal junction (D·E·J).',
    image: 'https://m.media-amazon.com/images/I/614xWE5O-bL._SX679_.jpg',
    price: 125.99,
    originalPrice: 250.99,
    rating: 4.5,
    reviews: 3421,
    category: 'Skin Care',
    affiliateLink: 'https://a.co/d/0aDtLv0H',
  },
  {
    id: 'f3-b',
    page: 'fashion',
    title: 'GRECERELLE 2026 Women Year-Round Casual Maxi',
    description: 'The GRECERELLE Long Maxi Dress with Pockets is your new go-to for every season. Featuring a loose, flowy fit, chic side slit, and zero wrinkles. Dress it down with sneakers or dress it up with heels and a belt! 👗',
    image: 'https://m.media-amazon.com/images/I/61ceyasLBOL._AC_SY879_.jpg',
    price: 19.99,
    originalPrice: 26.99,
    rating: 4.7,
    reviews: 2967,
    category: 'Women Dresses',
    affiliateLink: 'https://a.co/d/08wi48XV',
    featured: true,
  },
  {
    id: 'f3',
    page: 'fashion',
    title: 'WIHOLL Summer Dresses Cap Sleeve',
    description: 'The WIHOLL Summer Cap Sleeve Maxi Dress is a soft, lightweight polyester-spandex casual long dress featuring a classic crew neck, cap sleeves, functional side pockets, and a flowy fit ideal for beach vacations and summer wear.',
    image: 'https://m.media-amazon.com/images/I/71XHIDZUoqL._AC_SY879_.jpg',
    price: 12.99,
    originalPrice: 14.99,
    rating: 4.7,
    reviews: 2967,
    category: 'Women Dresses',
    affiliateLink: 'https://a.co/d/0hPy1MGB',
    featured: true,
  },
  {
    id: 'f4-c',
    page: 'fashion',
    title: 'Mens 2 Pieces Outfits Casual Polo Shirt and Shorts Set Collar Athletic Jogging Summer Tracksuit',
    description: 'Premium Fabric:The mens tracksuits set is crafted from high-quality fabric that is soft yet elastic,lightweight and breathable,ensuring you can move freely during your workout',
    image: 'https://m.media-amazon.com/images/I/71rg2sDkLiL._AC_SY879_.jpg',
    price: 34.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 16046,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/01UoSqWZ',
  },
   {
    id: 'f4-b',
    page: 'fashion',
    title: 'COOFANDY Men\'s Slim Fit Suit',
    description: 'a lightweight, breathable button-up top made from a cotton-linen rayon blend, featuring a relaxed fit, short sleeves, and a classic collar designed for beachwear, summer vacations, or casual everyday outfits.',
    image: 'https://m.media-amazon.com/images/I/81+oQBvBR-L._AC_SY879_.jpg',
    price: 29.99,
    originalPrice: 34.99,
    rating: 4.6,
    reviews: 16046,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/0bcBDGA3',
  },
    {
    id: 'f4',
    page: 'fashion',
    title: 'COOFANDY Mens Linen Shirts Short Sleeve Casual Shirts',
    description: 'a lightweight, breathable button-up shirt crafted from a cotton-linen blend, designed for comfortable everyday wear, beach outings, and summer events.',
    image: 'https://m.media-amazon.com/images/I/81TSrTXy8TL._AC_SY879_.jpg',
    price: 29.99,
    originalPrice: 31.99,
    rating: 4.4,
    reviews: 876,
    category: 'Men Dresses',
    affiliateLink: 'https://a.co/d/06eSEiA8',
  },
  {
    id: 'f5-c',
    page: 'fashion',
    title: 'Karseell Collagen Hair Mask for Dry, Frizzy, Damaged Hair ',
    description: 'All Hair Types: Suitable for all hair types dry/damaged/frizzy; fine hair caution; suitable for color treated and chemically processed hair; intended for hair lengths and ends and used away from scalp',
    image: 'https://m.media-amazon.com/images/I/71zGjIPmz8L._SL1500_.jpg',
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.3,
    reviews: 2789,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/06FSyZZd',
  },
   {
    id: 'f5-b',
    page: 'fashion',
    title: 'Nutrafol Men Hair Serum for Thinning Hair',
    description: 'Apply once daily directly to the scalp. Designed to work alongside daily hair growth supplements for optimal results.',
    image: 'https://m.media-amazon.com/images/I/616yx5sb7jL._SX522_.jpg',
    price: 49.99,
    originalPrice: 74.99,
    rating: 4.3,
    reviews: 2789,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/06ocnGxi',
  },
    {
    id: 'f5',
    page: 'fashion',
    title: 'Sulfate Free Hair Growth Product',
    description: 'a sulfate-free, color-safe conditioner that detangles, thickens, and nourishes fine or thinning hair without weighing it down.',
    image: 'https://m.media-amazon.com/images/I/51V5ikw1c9L._SX522_.jpg',
    price: 46.00,
    originalPrice: 54.99,
    rating: 4.6,
    reviews: 2104,
    category: 'Hair Products',
    affiliateLink: 'https://a.co/d/07xeGLXD',
  },
  {
    id: 'f6-b',
    page: 'fashion',
    title: 'TCL 52" Black Flush Mount Ceiling Fan with Light & Remote',
    description: 'Customizable Lighting: This ceiling fan comes with a 20W dimmable LED light, offering a more energy-efficient. The modern ceiling fan features three color temperatures—3000K warm light, 4000K natural ligh',
    image: 'https://m.media-amazon.com/images/I/51f-pn9cjeL._AC_SL1500_.jpg',
    price: 109.99,
    originalPrice: 159.99,
    rating: 4.5,
    reviews: 847,
    category: 'Home Decoration',
    affiliateLink: 'https://a.co/d/0e79Noxm',
  },
  {
    id: 'f6',
    page: 'fashion',
    title: 'Premium Aesthetic Faux Books for Room Decor',
    description: 'Made of durable, lightweight cardboard with printed matte covers. The books are completely hollow, do not open, have no interior pages, and do not provide storage space.',
    image: 'https://m.media-amazon.com/images/I/71QoYHSuC6L._AC_SL1500_.jpg',
    price: 24.99,
    originalPrice: 59.99,
    rating: 4.5,
    reviews: 847,
    category: 'Home Decoration',
    affiliateLink: 'https://a.co/d/05YKcRwn',
  },
  {
    id: 'f7-b',
    page: 'fashion',
    title: 'Prime Prometics PrimeLash Mascara for Older Woman (Black) | Volumizing, Incredible Length in 2 Coats, Long-Stay, Zero Clumps, Hypoallergenic',
    description: 'THICK, DEFINED AND LIFTED LASHES - In two clean coats. You will have lashes that make You look like a Million dollars. Thanks to the effective magic wand and formula duo.',
    image: 'https://m.media-amazon.com/images/I/51rjD1DyfpL._SX679_.jpg',
    price: 28.99,
    originalPrice: 36.99,
    rating: 4.2,
    reviews: 21309,
    category: 'Women Makeup',
    affiliateLink: 'https://a.co/d/04htNIAO',
  },
  {
    id: 'f7',
    page: 'fashion',
    title: 'LAURA GELLER Baked Balance-n-Brighten Powder',
    description: 'a lightweight, baked powder foundation handcrafted in Italy designed to self-adjust to your skin tone and even out complexion.',
    image: 'https://m.media-amazon.com/images/I/71RaNMySLgL._SL1500_.jpg',
    price: 32.99,
    originalPrice: 36.99,
    rating: 4.2,
    reviews: 21309,
    category: 'Women Makeup',
    affiliateLink: 'https://a.co/d/07kdaTZk',
  },

  // ===== TECH PRODUCTS =====
  {
    id: 't1-b',
    page: 'tech',
    title: 'Esinkin Bluetooth Audio Adapter for Music Streaming Sound System | Wireless Audio Adapter Works with Smartphones and Tablets, Bluetooth Receiver for Home Stereo',
    description: 'Works with most device: Bluetooth enabled device including smartphones, tablets, computers, laptops upon and any powered PC speakers, home stereo systems and A/V receivers.NOTE: This adapter doest ha',
    image: 'https://m.media-amazon.com/images/I/61HcKHv9M2L._AC_SX679_.jpg',
    price: 14.99,
    originalPrice: 16.99,
    rating: 4.8,
    reviews: 3421,
    category: 'Bluetooth Devices',
    affiliateLink:'https://a.co/d/0eyYtTzC',
    featured: true,
  },
  {
    id: 't1',
    page: 'tech',
    title: 'Apple MFi Certified Wallet Tracker Smart Card',
    description: 'an ultra-thin (2.5mm), credit card-shaped item locator that integrates natively with Apples Find My app to help you track lost wallets, passports, or luggage using a built-in 100dB speaker, long-lasting battery power, and IP68 water resistance.',
    image: 'https://m.media-amazon.com/images/I/71epei5xfnL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 14.99,
    originalPrice: 16.99,
    rating: 4.8,
    reviews: 3421,
    category: 'Bluetooth Devices',
    affiliateLink:'https://a.co/d/01mPpiTq',
    featured: true,
  },
  {
    id: 't2-b',
    page: 'tech',
    title: 'AROEVE Air Purifiers for Bedroom with Sleep Mode Speed Control-MK01A',
    description: 'High Circulation Rate: With dual-channel and 360-degree air inlets technology, AROEVE air purifier refreshes the air per hour in rooms up to 287 ft² / 25 m², covering every corner of the room to promote better health for you.',
    image: 'https://m.media-amazon.com/images/I/61A4iO11nrL._AC_SX679_.jpg',
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 2180,
    category: 'Tech Gadgets',
    affiliateLink: 'https://a.co/d/0e5Y5M1n',
    featured: true,
  },
  {
    id: 't2',
    page: 'tech',
    title: 'LISEN Retractable Car Charger',
    description: 'an 84-watt fast-charging cigarette lighter adapter featuring two 31.5-inch retractable cables (USB-C & Lightning), dual USB ports, and a 180° adjustable head to charge up to four devices simultaneously without cable clutter.',
    image: 'https://m.media-amazon.com/images/I/71Ryl5xKbuL._AC_SL1500_.jpg',
    price: 16.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviews: 2180,
    category: 'Tech Gadgets',
    affiliateLink: 'https://a.co/d/0hJ2nAVP',
    featured: true,
  },
  {
    id: 't3-b',
    page: 'tech',
    title: 'Steam Cleaner',
    description: '6-Level Adjustable Touch Control: Simply press the “+” or “-” buttons on the handheld steam cleaner to easily switch between six steam intensity settings to suit your cleaning needs. ',
    image: 'https://m.media-amazon.com/images/I/710EPs-7hML._AC_SL1500_.jpg',
    price: 49.99,
    originalPrice: 68.99,
    rating: 4.7,
    reviews: 1532,
    category: 'Kitchen Accessories',
    affiliateLink: 'https://a.co/d/01b6Yxua',
    featured: true,
  },
  {
    id: 't3',
    page: 'tech',
    title: 'Handheld Steam Cleaner',
    description: 'a chemical-free, pressurized steamer delivering 230°F continuous steam with a 350ML tank and 14 accessories for deep cleaning kitchen grease, bathroom grout, upholstery, and car interiors.',
    image: 'https://m.media-amazon.com/images/I/61ixIb6YrAL._AC_SX679_.jpg',
    price: 39.99,
    originalPrice: 45.99,
    rating: 4.7,
    reviews: 1532,
    category: 'Kitchen Accessories',
    affiliateLink: 'https://a.co/d/02g4JMaD',
    featured: true,
  },
  {
    id: 't4-b',
    page: 'tech',
    title: 'DREO 3L Humidifiers for Bedroom',
    description:  'Enjoy a serene sleep with DREOs 26dB (in Sleep Mode) whisper-quiet air humidifier, crafted for your babys ultimate comfort. Tailor your space with adjustable ambient lighting that can be turned on or off as needed.',
    image: 'https://m.media-amazon.com/images/I/618s2JAQmXL._AC_SL1500_.jpg',
    price: 28.99,
    originalPrice: 39.99,
    rating: 4.5,
    reviews: 932,
    category: 'Room Accessories',
    affiliateLink: 'https://a.co/d/0ffVygh5',
  },
  {
    id: 't4',
    page: 'tech',
    title: 'Air Purifiers for Home',
    description: 'covers large rooms up to 3,000 sq. ft. using a double-sided HEPA filtration system with a washable pre-filter, real-time PM2.5 air quality display, and an ultra-quiet 15dB sleep mode to capture pet dander, dust, pollen, and odors.',
    image: 'https://m.media-amazon.com/images/I/81KMChQ1-GL._AC_SX679_.jpg',
    price: 109.99,
    originalPrice: 139.99,
    rating: 4.5,
    reviews: 932,
    category: 'Room Accessories',
    affiliateLink: 'https://a.co/d/070YAy2x',
  },
  {
    id: 't5-b',
    page: 'tech',
    title: 'Endoscope Camera with Light',
    description: 'Endoscope Camera with Light,1920P HD Borescope Tools with 8 Adjustable LED Lights, Endoscope with Semi-Rigid Snake Camera, Inspection Borescope for iOS and Android-16.4ft Single Lens',
    image: 'https://m.media-amazon.com/images/I/71anyb4JreL._AC_SX679_.jpg',
    price: 30.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviews: 2945,
    category: 'Tech Tools',
    affiliateLink: 'https://a.co/d/05tyHwkz',
  },
  {
    id: 't5',
    page: 'tech',
    title: 'Fanttik E2 Ultra Electric Screwdriver',
    description: 'a 270 RPM rechargeable precision driver set featuring 5 adjustable torque settings (up to 0.6N.m), 50 magnetic S2 steel bits, and a pop-up RevoStor magnetic storage case designed for electronics, PCs, phones, and small appliances.',
    image: 'https://m.media-amazon.com/images/I/61q87lzcDhL._AC_SL1500_.jpg',
    price: 69.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviews: 2945,
    category: 'Tech Tools',
    affiliateLink: 'https://a.co/d/04ivYVxW',
  },
  {
    id: 't6-b',
    page: 'tech',
    title: 'Sceptre 24-inch Prime Monitor Thin',
    description: 'Sceptre 24-inch Prime Monitor Thin 1080p LED Monitor 99% sRGB 2x HDMI VGA Build-in Speakers, Machine Black (E248W-19203R 2025 Series) | Thin 1080p LED 99% sRGB 2x HDMI VGA Build-in Speakers, Machine Black (Series)',
    image: 'https://m.media-amazon.com/images/I/61+-pmJOYjL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 81.99,
    originalPrice: 100.00,
    rating: 4.6,
    reviews: 4521,
    category: 'Mobile & Desktop',
    affiliateLink: 'https://a.co/d/08scO7z6',
    featured: true,
  },
   {
    id: 't6',
    page: 'tech',
    title: 'Adjustable Height Mobile Computer Desk',
    description: 'a compact, rolling laptop workstation featuring a 31.5" x 15.75" waterproof desktop, smooth-gliding caster wheels, 28" to 35" height adjustment, and built-in lower storage shelves for small spaces.',
    image: 'https://m.media-amazon.com/images/I/61oEmrjwoAL._AC_SX679_.jpg',
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 4521,
    category: 'Mobile & Desktop',
    affiliateLink: 'https://a.co/d/0gANQlSu',
    featured: true,
  },
  {
    id: 't7-b',
    page: 'tech',
    title: 'dbsono Portable Bluetooth Speaker Wireless',
    description: '100W Peak, Bluetooth 6.0, Black | SoundPulse 2.0, Bass Boost, USB-C Audio, Multi-Speaker Pairing, Waterproof, TWS stereo for indoor and outdoor listening',
    image: 'https://m.media-amazon.com/images/I/81ZFinKGAjL._AC_SX679_.jpg',
    price: 139.99,
    originalPrice: 165.99,
    rating: 4.5,
    reviews: 1876,
    category: 'Speakers',
    affiliateLink: 'https://a.co/d/08ReEltQ',
  },
  {
    id: 't7',
    page: 'tech',
    title: 'Amazon Basics Stereo 2.0 Speakers for PC or Laptop with Volume Control',
    description: 'a compact, USB-powered desk speaker pair featuring 3.5mm AUX connectivity, in-line volume control, blue LED accent lighting, and bottom passive radiators for enhanced bass performance.',
    image: 'https://m.media-amazon.com/images/I/71VUfk4MzJL._AC_SL1500_.jpg',
    price: 23.99,
    originalPrice: 25.99,
    rating: 4.5,
    reviews: 1876,
    category: 'Speakers',
    affiliateLink: 'https://a.co/d/0gZ8jGoS',
  },
  
  // ===== GAMING PRODUCTS =====
  {
    id: 'g1-c',
    page: 'gaming',
    title: 'Razer Basilisk V3 Pro Customizable RGB Wireless Gaming Mouse, Black',
    description: 'Elevate your gaming with the Razer Basilisk V3 Pro—a high-performance wireless gaming mouse featuring 10+1 programmable controls, Razer Focus Pro 30K Optical Sensor, Razer HyperScroll Tilt Wheel, and 13-zone Chroma RGB lighting. Built for seamless precision and ultimate customization.',
    image: 'https://m.media-amazon.com/images/I/71L-flqtTwL._AC_SL1500_.jpg',
    price: 99.00,
    originalPrice: 159.00,
    rating: 4.8,
    reviews: 2341,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/090icyQh',
    featured: true,
  },
  {
    id: 'g1-b',
    page: 'gaming',
    title: ' Wireless Gaming Mouse - Black',
    description: 'The Logitech G PRO X Superlight 2 is an ultra-lightweight (60g), high-performance wireless esports gaming mouse featuring an advanced HERO 2 sensor with up to 44,000 DPI and hybrid LIGHTFORCE optical-mechanical switches.',
    image: 'https://m.media-amazon.com/images/I/51Cps60NQpL._AC_SL1500_.jpg',
    price: 144.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviews: 2341,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/0hpzBnyj',
    featured: true,
  },
  {
    id: 'g1',
    page: 'gaming',
    title: 'Wireless RGB Gaming Mouse',
    description: 'hybrid LIGHTFORCE optical-mechanical switches, 8-zone LIGHTSYNC RGB lighting, a HERO 25K sensor, 13 customizable controls, and up to 130 hours of battery life with USB-C and PowerPlay wireless charging compatibility.',
    image: 'https://m.media-amazon.com/images/I/61A0MX5s2xL._AC_SL1500_.jpg',
    price: 148.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviews: 876,
    category: 'Mouse',
    affiliateLink: 'https://a.co/d/04f9lNcN',
    featured: true,
  },
  {
    id: 'g3-c',
    page: 'gaming',
    title: ' Prime Gaming Monitor Display',
    description: 'Level up your setup with the Sceptre 24-inch Prime Gaming Monitor (E248B-FW165T). Engineered for competitive play, it features a fluid 165Hz refresh rate, 1ms response time, Full HD 1080p resolution, and Adaptive Sync to eliminate lag and screen tearing. Equipped with dual HDMI ports, dual DisplayPorts, and built-in speakers for ultimate multi-device connectivity and immersive audio.',
    image: 'https://m.media-amazon.com/images/I/71VQX048EVL._AC_SX679_.jpg',
    price: 81.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0iEC5xv9',
    featured: true,
  },
    {
    id: 'g3-b',
    page: 'gaming',
    title: 'Amazon Basics 24 Inch (23.8 inch viewable) Monitor',
    description: 'a 1080p Full HD IPS display with a 100Hz refresh rate, built-in speakers, and VESA mount compatibility for office and casual entertainment use.',
    image: 'https://m.media-amazon.com/images/I/710ZLpqfQeL._AC_SY450_.jpg',
    price: 83.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0d3Z86PT',
    featured: true,
  },
  {
    id: 'g3',
    page: 'gaming',
    title: 'Office Monitor',
    description: 'a 1080p Full HD IPS display with a smooth 120Hz refresh rate, 1ms VRB response time, Adaptive-Sync, and blue light filtering for comfortable daily productivity and light gaming.',
    image: 'https://m.media-amazon.com/images/I/71e5GgPXQzL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    price: 99.99,
    originalPrice: 149.99,
    rating: 4.7,
    reviews: 1543,
    category: 'Monitors',
    affiliateLink: 'https://a.co/d/0gAGupN9',
    featured: true,
  },
  {
    id: 'g4-c',
    page: 'gaming',
    title: 'Lumbar Support Pillow for Office Chair',
    description: 'Say goodbye to back pain with this Ergonomic Lumbar Support Pillow. Designed to improve posture and relieve lower back pressure, it features breathable mesh fabric, dual adjustable straps for a secure fit, and high-density memory foam support. Perfect for office chairs, car seats, or gaming setups, making it an ideal, thoughtful gift for everyday comfort.',
    image: 'https://m.media-amazon.com/images/I/81Qm1-Fja2L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 26.00,
    originalPrice: 50.99,
    rating: 4.6,
    reviews: 1098,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/02Q2GxlI',
  },
  {
    id: 'g4-b',
    page: 'gaming',
    title: 'GTPLAYER Gaming Chair',
    description: 'Upgrade your seating experience with the GTPLAYER Ergonomic Gaming Chair. Designed for long hours of gaming or work, it features a retractable footrest, adjustable lumbar support, removable headrest pillow, and a 360° swivel base. Wrapped in sleek, durable black faux leather, it delivers maximum comfort, stability, and style for any gaming setup or home office.',
    image: 'https://m.media-amazon.com/images/I/61phC8Ix9bL._AC_SX679_.jpg',
    price: 109.99,
    originalPrice: 169.99,
    rating: 4.6,
    reviews: 16698,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/0iVVT567',
  },
  {
    id: 'g4',
    page: 'gaming',
    title: 'TRALT Office Chair Ergonomic Desk Chair',
    description: 'a high-density molded foam seat, depth-adjustable lumbar support, a breathable mesh backrest, flip-up armrests, an adjustable headrest, and a heavy-duty base supporting up to 330 lbs.',
    image: 'https://m.media-amazon.com/images/I/81OW9VpP4qL._AC_SL1500_.jpg',
    price: 139.99,
    originalPrice: 159.99,
    rating: 4.6,
    reviews: 1098,
    category: 'Chair',
    affiliateLink: 'https://a.co/d/05AvMSrt',
  },
  {
    id: 'g5-c',
    page: 'gaming',
    title: 'GameSir G7 SE Wired Controller',
    description: 'Master your gameplay with the GameSir G7 SE Wired Controller for Xbox Series X|S, Xbox One, and Windows 10/11. Built with anti-drift Hall Effect joysticks and precision Hall Effect analog triggers, this plug-and-play gamepad ensures ultra-long durability and zero stick drift. Features quick-latch back buttons, a 3.5mm audio jack, and a customizable faceplate in a clean white design.',
    image: 'https://m.media-amazon.com/images/I/51iXILIT27L._SX522_.jpg',
    price: 44.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 3210,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0cUX2dlS',
  },
  {
    id: 'g5-b',
    page: 'gaming',
    title: 'GameSir G7 Pro Wired Controller for Xbox Series',
    description: 'Take control with the GameSir G7 Pro Controller, designed for Xbox Series X|S, Xbox One, PC, and Android. Engineered for ultra-precise inputs, it features anti-drift TMR sticks, Hall Effect analog triggers, and a fast 1000Hz polling rate on PC. Complete with dual rumble motors, a 3.5mm audio jack, and a sleek white finish for high-performance competitive gaming.',
    image: 'https://m.media-amazon.com/images/I/719XHbmvmBL._SX522_.jpg',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 3210,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0hkJzdhh',
  },
  {
    id: 'g5',
    page: 'gaming',
    title: 'Seagate 2TB Game Drive for Xbox',
    description: 'an officially licensed external USB 3.0 hard drive featuring 2TB of portable storage, built-in Xbox green LED lighting, plug-and-play setup for archiving Xbox Series X|S games, and playing Xbox One titles directly.',
    image: 'https://m.media-amazon.com/images/I/416kbEX-pVL._AC_SL1500_.jpg',
    price: 119.99,
    originalPrice: 139.99,
    rating: 4.7,
    reviews: 3210,
    category: 'Xbox Accessories',
    affiliateLink: 'https://a.co/d/0aqCkwHW',
  },
  {
    id: 'g6-e',
    page: 'gaming',
    title: 'Led Desk Lamp for Office Home - Eye Caring Architect lamp',
    description: 'Illuminate your workspace with this 24W Dual-Screen LED Desk Lamp. Designed for dual-monitor setups, drafting, and studying, it features an eye-caring, flicker-free architect arm with a space-saving clamp. With 5 adjustable color temperatures and flexible positioning, it delivers wide, customizable lighting to enhance focus and reduce eye strain during long work or study sessions.',
    image: 'https://m.media-amazon.com/images/I/616md8tdywL._AC_SL1080_.jpg',
    price: 46.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/00mtROIz',
  },
  {
    id: 'g6-d',
    page: 'gaming',
    title: 'Govee RGBIC Smart Table Lamp 2, Touch Bedside Small Table Lamp (Corded)',
    description: 'Elevate your space with the Govee RGBIC Smart Table Lamp 2. Designed with advanced RGBIC technology to display multiple colors at once, this compact corded bedside lamp features intuitive touch controls, customizable lighting effects, and seamless app or voice control. Perfect for nightstands, gaming desks, or creating a cozy, colorful atmosphere anywhere in your home.',
    image: 'https://m.media-amazon.com/images/I/618yTEtHltL._AC_SL1500_.jpg',
    price: 63.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/0do989EV',
  },
  {
    id: 'g6-c',
    page: 'gaming',
    title: 'Govee RGBIC Floor Lamp Basic, 1000lm LED Corner Lamp, Black',
    description: 'Transform your rooms atmosphere with the Govee RGBIC Floor Lamp Basic. Delivering 1000 lumens of brightness, this sleek black corner lamp features advanced RGBIC technology to display multiple colors simultaneously along a single line. Enjoy customizable dynamic light effects, music sync mode, and effortless hands-free voice control via Alexa and Google Assistant—perfect for gaming setups, living rooms, and bedrooms.',
    image: 'https://m.media-amazon.com/images/I/61SdRNLwZzL._AC_SX342_SY445_QL70_FMwebp_.jpg',
    price: 64.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/02sYYGtj',
  },
  {
    id: 'g6-b',
    page: 'gaming',
    title: 'Airlonv LED Desk Lamp with Clamp, 17" Stepless Dimming Light, Black',
    description: 'Brighten your workspace with the Airlonv LED Desk Lamp with Clamp. Featuring a 17" light bar, stepless dimming, and adjustable color temperatures, this eye-caring desk lamp provides customizable, flicker-free illumination. Its flexible gooseneck and space-saving clamp design easily attach to any desk, making it ideal for studying, working, reading, or crafting.',
    image: 'https://m.media-amazon.com/images/I/71Xa0fzUiGL._AC_SX342_SY445_QL70_FMwebp_.jpg',
    price: 19.99,
    originalPrice: 25.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/08cArnVF',
  },
  {
    id: 'g6',
    page: 'gaming',
    title: 'Govee Uplighter Floor Lamp for Living Room',
    description: 'a 330° rotating lamp head with a dynamic RGBIC water ripple projector, tri-zone lighting control with 1,000lm task lighting',
    image: 'https://m.media-amazon.com/images/I/81bgKHOSSWL._AC_SL1500_.jpg',
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.5,
    reviews: 4521,
    category: 'Room Light',
    affiliateLink: 'https://a.co/d/0aoJSjbE',
  },
  {
    id: 'g7-b',
    page: 'gaming',
    title: 'Wireless Switch Controller',
    description: 'Elevate your gaming with this Multi-Platform Wireless Switch Controller, fully compatible with Nintendo Switch, Switch 2, Lite, and OLED models. Engineered for elite control, it features back buttons with a tactile mouse-click feel, customizable programming, turbo speed settings, and a one-key console wake-up function for seamless, ultra-responsive play.',
    image: 'https://m.media-amazon.com/images/I/71fQOXATOML._SL1500_.jpg',
    price: 26.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviews: 765,
    category: 'Switch Accessories',
    affiliateLink: 'https://a.co/d/0en1AD1H',
  },
    {
    id: 'g7',
    page: 'gaming',
    title: 'Orzly Carrying Case for Nintendo Switch 2 2025 Console with Screen Padding',
    description: 'Protect your next-gen console on the go with the Orzly Carrying Case designed for the Nintendo Switch 2. Featuring dedicated screen padding, hard EVA shell protection, and organized storage pockets for game cards and accessories, this compact travel case keeps your setup secure, scratch-free, and ready for action wherever you go.',
    image: 'https://m.media-amazon.com/images/I/812xPtswK9L._SL1500_.jpg',
    price: 26.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 765,
    category: 'Switch Accessories',
    affiliateLink: 'https://a.co/d/04pf0H8l',
  },
  {
    id: 'g8',
    page: 'gaming',
    title: 'Gaming Router ',
    description: 'features dual 2.5G multi-gigabit ports, 8-stream Wi-Fi 6 speeds up to 6 Gbps, pre-installed OpenWrt software, high-speed WireGuard VPN support, and built-in AdGuard Home.',
    image: 'https://m.media-amazon.com/images/I/51CImYagh1L._AC_SL1000_.jpg',
    price: 169.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviews: 765,
    category: 'Router',
    affiliateLink: 'https://a.co/d/0eabphWM',
  },
  {
    id: 'g9-b',
    page: 'gaming',
    title: 'Laptop Lap Desk for Bed, SAIJI X-Large Adjustable Laptop Table',
    description: 'Work or relax in complete comfort with the SAIJI X-Large Adjustable Laptop Lap Desk. Designed for beds, couches, and floor setups, it features adjustable height and tilt angles, a spacious surface for large laptops and accessories, and a foldable design for easy storage. Built with a non-slip ledge and sturdy construction, its the ultimate workstation for working, studying, or lounging.',
    image: 'https://m.media-amazon.com/images/I/71nLTaB-KvL._AC_SL1500_.jpg',
    price: 69.99,
    originalPrice: 89.99,
    rating: 4.8,
    reviews: 2890,
    category: 'Storage',
    affiliateLink: 'https://a.co/d/0eyE9izt',
  },
   {
    id: 'g9',
    page: 'gaming',
    title: 'Seagate Portable 2TB External Hard Drive',
    description: 'offers easy plug-and-play drag-and-drop storage with USB 3.0 connectivity, universal compatibility for PC, Mac, PlayStation, and Xbox, an included 18-inch USB cable, and 1-Year Rescue Data Recovery Services.',
    image: 'https://m.media-amazon.com/images/I/61EFaBPAnVL._AC_SL1500_.jpg',
    price: 156.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviews: 2890,
    category: 'Storage',
    affiliateLink: 'https://a.co/d/075RweKX',
  },
  {
    id: 'g10-c',
    page: 'gaming',
    title: ' L Shaped Office Desk with Power Outlets and Type-C Port',
    description: 'Maximize your corner space with this 55-Inch L-Shaped Gaming & Office Desk in Rustic Brown. Built for ultimate productivity and organization, it features integrated power outlets and a Type-C port for fast device charging, 3 spacious fabric drawers, and open mesh storage shelves. Its sturdy steel frame and expansive surface make it ideal for dual-monitor gaming setups, home offices, or study spaces.',
    image: 'https://m.media-amazon.com/images/I/81dAwnxUDkL._AC_SX679_.jpg',
    price: 109.99,
    originalPrice: 119.99,
    rating: 4.5,
    reviews: 1678,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/09A7MCt2',
  },
  {
    id: 'g10-b',
    page: 'gaming',
    title: 'Japanese Mouse Pad',
    description: 'Upgrade your desk setup with this XL Japanese Anime Mouse Pad (31.5” x 11.8”). Designed to fit both your keyboard and mouse, it features vibrant Japanese artwork, smooth tracking fabric for effortless cursor movement, stitched anti-fray edges, and a heavy-duty non-slip rubber base. Perfect for gaming, working, or adding an aesthetic touch to your home office.',
    image: 'https://m.media-amazon.com/images/I/71sIHaXtpOL._AC_SL1500_.jpg',
    price: 14.99,
    originalPrice: 34.99,
    rating: 4.5,
    reviews: 1678,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/0bsUfUhs',
  },
  {
    id: 'g10',
    page: 'gaming',
    title: 'Aothia Leather Office Desk Pad Protector',
    description: 'features a 31.5" x 15.7" waterproof PU leather surface with a non-slip suede backing, serving as a dual desk blotter and writing mouse pad to protect surfaces from scratches, spills, and daily wear.',
    image: 'https://m.media-amazon.com/images/I/81A14OTXb9L._AC_SX300_SY300_QL70_FMwebp_.jpg',
    price: 13.99,
    originalPrice: 34.99,
    rating: 4.5,
    reviews: 1678,
    category: 'Desk Pads',
    affiliateLink: 'https://a.co/d/02dOO5fP',
  },
  {
    id: 'g11-b',
    page: 'gaming',
    title: 'llano V12 Gaming Laptop Cooling Pad Laptop Cooler Laptop Cooling Fan Stand',
    description: 'Keep your laptop running at peak performance with the llano V12 Gaming Laptop Cooling Pad. Engineered with high-speed industrial-grade cooling fans and an airtight foam seal, it drastically lowers CPU and GPU temperatures during intense gaming sessions. Features adjustable wind speeds, customizable RGB lighting modes, and an ergonomic height-adjustable stand to prevent overheating and thermal throttling.',
    image: 'https://m.media-amazon.com/images/I/71t9L9oIYhL._AC_SL1500_.jpg',
    price: 95.99,
    originalPrice: 119.99,
    rating: 4.6,
    reviews: 543,
    category: 'PC Accessories',
    affiliateLink: 'https://a.co/d/0eX1qlpV',
  },
  {
    id: 'g11',
    page: 'gaming',
    title: 'Ultimate 2 Wireless Controller for PC',
    description: 'switchable Hall Effect and tactile triggers, an ultra-low latency 1000Hz polling rate via 8Speed 2.4G wireless, RGB Fire Ring lighting, extra back paddle buttons, and an included charging dock.',
    image: 'https://m.media-amazon.com/images/I/31DK+auiqfL._SX342_SY445_QL70_FMwebp_.jpg',
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviews: 543,
    category: 'PC Accessories',
    affiliateLink: 'https://a.co/d/0b72MatL',
  },
  {
    id: 'g12-c',
    page: 'gaming',
    title: 'BENGOO G9000 Stereo Gaming Headset',
    description: 'Immerse yourself in every game with the BENGOO G9000 Stereo Gaming Headset. Equipped with 7.1 surround sound drivers, a noise-isolating omnidirectional microphone, and comfortable soft memory earmuffs, this multi-platform headset delivers crystal-clear audio and all-day comfort. Features built-in LED lighting and 3.5mm jack compatibility for PS5, PS4, Xbox Series X|S, Xbox One, PC, and Nintendo Switch.',
    image: 'https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SL1000_.jpg',
    price: 19.99,
    originalPrice: 29.99,
    rating: 4.4,
    reviews: 432,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/0a5aIiC4',
  },
  {
    id: 'g12-b',
    page: 'gaming',
    title: 'YEEBAY Target Shooting Toys',
    description: 'Bring active, safe fun to playtime with the YEEBAY Target Shooting Toys Set. Designed for kids ages 6 and up, this high-energy game includes a standing scoring target board, foam ball air guns, and soft, lightweight foam balls for safe indoor or outdoor play. Perfect for improving hand-eye coordination, active family fun, and friendly competition.',
    image: 'https://m.media-amazon.com/images/I/71psM3gJHSL._AC_SX679_.jpg',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 432,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/0asR2GnX',
  },
  {
    id: 'g12',
    page: 'gaming',
    title: 'LEGO Super Mario Game Boy',
    description: 'a 421-piece, near 1:1 scale collectible model kit for adults featuring interactive buttons, interchangeable Game Paks, lenticular game screens, and a buildable display stand.',
    image: 'https://m.media-amazon.com/images/I/71AV0wHyDUL._AC_SX679_.jpg',
    price: 59.99,
    originalPrice: 68.99,
    rating: 4.4,
    reviews: 432,
    category: 'Collectables',
    affiliateLink: 'https://a.co/d/06bKd4xz',
  },
  {
    id: 'g13-b',
    page: 'gaming',
    title: 'Cooling Station with LED Controller Charging Station for PlayStation',
    description: 'Immerse yourself in every game with the BENGOO G9000 Stereo Gaming Headset. Equipped with 7.1 surround sound drivers, a noise-isolating omnidirectional microphone, and comfortable soft memory earmuffs, this multi-platform headset delivers crystal-clear audio and all-day comfort. Features built-in LED lighting and 3.5mm jack compatibility for PS5, PS4, Xbox Series X|S, Xbox One, PC, and Nintendo Switch.',
    image: 'https://m.media-amazon.com/images/I/713asLPZglL._AC_SL1500_.jpg',
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.5,
    reviews: 621,
    category: 'Merchandise',
    affiliateLink: 'https://a.co/d/09FcyMTu',
  },
  {
    id: 'g13',
    page: 'gaming',
    title: 'Funko POP! Games: Pokemon ',
    description: 'an officially licensed vinyl figurine standing approximately 5.15 inches tall, perfect for shelf display or as a collectible for Pokémon fans.',
    image: 'https://m.media-amazon.com/images/I/71HjHpzxdIL._AC_SL1500_.jpg',
    price: 15.99,
    originalPrice: 24.99,
    rating: 4.5,
    reviews: 621,
    category: 'Merchandise',
    affiliateLink: 'https://a.co/d/0iaDIklu',
  },

  // ===== FITNESS PRODUCTS =====
  {
    id: 'fi1-b',
    page: 'fitness',
    title: 'MERACH Exercise Bike, Magnetic Friction Stationary Bike for Home',
    description: 'Achieve your fitness goals at home with the MERACH Magnetic Stationary Exercise Bike. Designed for a smooth, whisper-quiet ride, it features adjustable magnetic resistance, a heavy-duty steel frame, and an ergonomic padded seat for maximum comfort. Complete with a digital monitor to track your workout metrics and an integrated device holder, its the perfect compact solution for low-impact cardio workouts.',
    image: 'https://m.media-amazon.com/images/I/71l+KL4uazL._AC_SX679_.jpg',
    price: 269.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 2104,
    category: 'Weights',
    affiliateLink: 'https://a.co/d/0hcCjGbr',
    featured: true,
  },
  {
    id: 'fi1',
    page: 'fitness',
    title: 'Zeerun Weighted Vest',
    description: 'made from skin-friendly, leak-proof neoprene with double-stitched seams, thick shoulder padding, adjustable front buckles, and safety reflective stripes for walking, rucking, and strength training.',
    image: 'https://m.media-amazon.com/images/I/81zh-RIi18L._AC_SL1500_.jpg',
    price: 14.99,
    originalPrice: 35.99,
    rating: 4.8,
    reviews: 2104,
    category: 'Weights',
    affiliateLink: 'https://a.co/d/0hfVbnh5',
    featured: true,
  },

  {
    id: 'fi2-b',
    page: 'fitness',
    title: 'Jocko Mölk 30g Grass Fed Protein Shakes',
    description: 'Fuel your body with Jocko Mölk Ready-to-Drink Chocolate Protein Shakes. Packed with 30g of grass-fed protein, zero added sugar, and low net carbs, this keto-friendly shake delivers a smooth, delicious chocolate taste without artificial sweeteners. Perfectly formulated for muscle recovery, clean energy, and convenient on-the-go nutrition in a ready-to-drink 12 fl oz pack.',
    image: 'https://m.media-amazon.com/images/I/81dUI1WWhQL._SX679_.jpg',
    price: 44.99,
    originalPrice: 69.99,
    rating: 4.7,
    reviews: 5430,
    category: 'Supplements',
    affiliateLink: 'https://a.co/d/00rYUxdC',
    featured: true,
  },
  {
    id: 'fi2',
    page: 'fitness',
    title: 'Protein Shaker Bottle for Protein Mixes',
    description: 'a 100% leak-proof design, six wire whisks for clump-free mixing, stackable BPA-free plastic construction, and dishwasher-safe convenience in an Earth Tones color collection.',
    image: 'https://m.media-amazon.com/images/I/812Aa6MATwL._AC_SY879_.jpg',
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.7,
    reviews: 5430,
    category: 'Supplements',
    affiliateLink: 'https://a.co/d/0bd7myWd',
    featured: true,
  },
  {
    id: 'fi3-b',
    page: 'fitness',
    title: 'TRX GO Suspension Trainer',
    description: 'Achieve a full-body workout anywhere with the TRX GO Suspension Trainer. Lightweight, portable, and easy to set up in seconds, this bodyweight training system lets you burn fat, build lean muscle, and strengthen your core using your own body weight. Comes complete with indoor/outdoor anchors and a travel pouch—perfect for home workouts, travel, or training on the go.',
    image: 'https://m.media-amazon.com/images/I/71fWIMZHGeL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 111.99,
    originalPrice: 139.99,
    rating: 4.6,
    reviews: 1432,
    category: 'Travel',
    affiliateLink: 'https://a.co/d/08w4Gzca',
  },
  {
    id: 'fi3',
    page: 'fitness',
    title: 'VINSGUIR Ab Roller Wheel',
    description: 'a 3.2-inch ultra-wide dual wheel with non-slip EVA rubber cotton handles, a high-strength stainless steel shaft supporting up to 440 lbs, and an included knee pad for extra comfort during core strength workouts.',
    image: 'https://m.media-amazon.com/images/I/71CH7yY6m2L._AC_SX679_.jpg',
    price: 23.99,
    originalPrice: 29.99,
    rating: 4.6,
    reviews: 1432,
    category: 'Travel',
    affiliateLink: 'https://a.co/d/0198ptTE',
  },
  {
    id: 'fi4-b',
    page: 'fitness',
    title: 'Lifepro Waver Vibration Plate Exercise Machine with 99 Speeds & 10 Presets',
    description: 'Enhance your workouts and accelerate recovery with the Lifepro Waver Vibration Plate Exercise Machine. Designed to stimulate muscles, boost circulation, and aid weight loss through full-body vibrations, this platform features 99 speed levels and 10 pre-set program modes. Equipped with loop bands, resistance straps, and a user-friendly remote control, its the ultimate low-impact addition to your home fitness routine.',
    image: 'https://m.media-amazon.com/images/I/71VaXGNl5pL._SX522_.jpg',
    price: 199.99,
    originalPrice: 229.99,
    rating: 4.5,
    reviews: 876,
    category: 'Machines',
    affiliateLink: 'https://a.co/d/0bDkaQ8a',
  },
  {
    id: 'fi4',
    page: 'fitness',
    title: 'Vibration Plate Fitness Platform Exercise Machine Body',
    description: 'Compact folding treadmill with 3HP motor, 12 programs, and Bluetooth app sync.',
    image: 'https://m.media-amazon.com/images/I/71q91XoN2IL._AC_SX679_.jpg',
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviews: 876,
    category: 'Machines',
    affiliateLink: 'https://a.co/d/07loBarI',
  },
  {
    id: 'fi5-b',
    page: 'fitness',
    title: 'Garmin vívoactive® 6, Health & Fitness GPS Smartwatch, 42mm, Slate',
    description: 'Track your wellness and elevate your active lifestyle with the Garmin vívoactive® 6 Health & Fitness GPS Smartwatch (42mm, Slate). Featuring a bright AMOLED display and up to 11 days of battery life, this sleek smartwatch delivers comprehensive 24/7 health tracking, including Body Battery™ energy monitoring, Sleep Coach, HRV status, and daily stress insights. With over 80 built-in sports apps, Garmin Coach adaptive training plans, contactless payments, and onboard music storage, its designed to seamlessly guide your fitness journey from workout to rest.  ',
    image: 'https://m.media-amazon.com/images/I/611jnYHa1OL._AC_SL1500_.jpg',
    price: 299.99,
    originalPrice: 339.99,
    rating: 4.5,
    reviews: 2654,
    category: 'Tracking Device',
    affiliateLink: 'https://a.co/d/0fNBMPN6',
  },
   {
    id: 'fi5',
    page: 'fitness',
    title: 'Google Fitbit Air Special Edition Stephen Curry - Screenless Tracker',
    description: 'a distraction-free screenless design, 24/7 heart rate and sleep tracking, a sweatproof water-resistant coating, personalized AI-powered coaching via Google Health Premium, and up to 7 days of battery life.',
    image: 'https://m.media-amazon.com/images/I/71FS8LWK7QL._AC_SX679_.jpg',
    price: 129.99,
    originalPrice: 139.99,
    rating: 4.5,
    reviews: 2654,
    category: 'Tracking Device',
    affiliateLink: 'https://a.co/d/01RzlUMI',
  },
  {
    id: 'fi6-b',
    page: 'fitness',
    title: 'HydroJug Traveler 40oz, Insulated Tumbler with Handle & Straw, Cream',
    description: 'Stay hydrated in style with the HydroJug Traveler 40oz Insulated Tumbler in Cream. Featuring double-wall stainless steel insulation, a spill-proof lid with a built-in flip straw, and a comfortable ergonomic handle, this sleek travel mug keeps your drinks ice-cold all day long. Designed to fit standard cup holders, its the ultimate everyday companion for workouts, commutes, and daily routine.',
    image: 'https://m.media-amazon.com/images/I/51rnEI9emNL._AC_SX679_.jpg',
    price: 31.00,
    originalPrice: 59.99,
    rating: 4.7,
    reviews: 4321,
    category: 'Water Bottles',
    affiliateLink: 'https://a.co/d/0ik3s3Pg',
  },
  {
    id: 'fi6',
    page: 'fitness',
    title: 'RAYMYLO One Gallon Water Bottle Insulated',
    description: 'features 128 oz triple-walled vacuum stainless steel insulation that keeps drinks cold up to 48 hours, leak-proof straw and spout lids, a carrying pouch, a functional paracord handle with a compass and carabiner, and included cleaning brushes.',
    image: 'https://m.media-amazon.com/images/I/71IL2cwmmqL._AC_SL1500_.jpg',
    price: 44.98,
    originalPrice: 59.99,
    rating: 4.7,
    reviews: 4321,
    category: 'Water Bottles',
    affiliateLink: 'https://a.co/d/034vp6XJ',
  },
  {
    id: 'fi7-b',
    page: 'fitness',
    title: 'Ally Peaks Pull Up Bar for Doorway',
    description: 'Transform any doorway into a personal home gym with the Ally Peaks Pull-Up Bar. Crafted from heavy-duty thickened steel with a maximum weight capacity of 440 lbs, this portable workout bar features multi-grip padded foam handles to target your back, chest, arms, and core. Designed for simple, screw-free door frame installation, it allows you to perform chin-ups, pull-ups, dips, and sit-ups with ease.',
    image: 'https://m.media-amazon.com/images/I/61Ai3fZLi9L._AC_SL1500_.jpg',
    price: 28.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 765,
    category: 'CrossFit',
    affiliateLink: 'https://a.co/d/0ekuijMC',
  },
  {
    id: 'fi7',
    page: 'fitness',
    title: 'Push Up Board',
    description: 'a durable ABS construction supporting up to 300 kg (660 lbs), non-slip silicone handles with built-in storage, and a portable folding design.',
    image: 'https://m.media-amazon.com/images/I/71PEbWkLmoL._AC_SL1500_.jpg',
    price: 31.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviews: 765,
    category: 'CrossFit',
    affiliateLink: 'https://a.co/d/0fu7eO4e',
  },
  {
    id: 'fi8-b',
    page: 'fitness',
    title: 'Jump Rope',
    description: 'Achieve your fitness and cardio goals with this Tangle-Free Rapid Speed Jump Rope. Featuring high-speed 360° ball bearings for smooth, snag-free rotation and a durable steel cable, its built to handle high-intensity workouts, double-unders, and daily cardio sessions. Designed with soft, anti-slip foam handles and a fully adjustable rope length, it offers a custom, comfortable fit for adults and kids alike.',
    image: 'https://m.media-amazon.com/images/I/71wm42EtoNL._AC_SX679_.jpg',
    price: 8.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviews: 1876,
    category: 'Home Workout',
    affiliateLink: 'https://a.co/d/0bbUH3Di',
  },
  {
    id: 'fi8',
    page: 'fitness',
    title: 'FLYBIRD WB5 Weight Bench',
    description: 'The FLYBIRD WB5 Weight Bench is an ASTM-certified, 800 lb heavy-duty workout bench featuring a 30-inch extended backrest, a 3-step foldable space-saving design, spring-lock adjustments from -30° to 90° for flat, incline, and decline training, and an adjustable leveling footpad.',
    image: 'https://m.media-amazon.com/images/I/71ijsNeaN-L._AC_SL1500_.jpg',
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviews: 1876,
    category: 'Home Workout',
    affiliateLink: 'https://a.co/d/06gcSAsx',
  },
  {
    id: 'fi9',
    page: 'fitness',
    title: 'NICEPEOPLE Adjustable Weight Bench for Home Gym',
    description: 'a 660 lb capacity alloy steel frame with 8 adjustable backrest angles, high-density sweat-resistant leather padding, 4 rotatable leveling foot caps, and a 1-step foldable space-saving design for small apartments.',
    image: 'https://m.media-amazon.com/images/I/719zG2ZrQzL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 62.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 1098,
    category: 'Outdoor',
    affiliateLink: 'https://a.co/d/0eegAVtJ',
  },
  {
    id: 'fi10',
    page: 'fitness',
    title: 'Under Desk Elliptical Machine',
    description: '12 adjustable manual speed levels and automatic modes (P1-P3), forward and reverse pedal motion, ultra-quiet sound-dampening technology, real-time LCD tracking, and an included remote control for zero-assembly seated leg exercise.',
    image: 'https://m.media-amazon.com/images/I/71XJsK7LnIL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 84.99,
    originalPrice: 99.99,
    rating: 4.4,
    reviews: 1342,
    category: 'Strength',
    affiliateLink: 'https://a.co/d/0h175f7j',
  },
  {
    id: 'fi11',
    page: 'fitness',
    title: 'YOLEO Adjustable Weight Bench',
    description: 'The YOLEO Adjustable Weight Bench features an ASTM-certified 827 lb capacity heavy-duty alloy steel frame, 84 adjustable angle combinations (7 backrest, 4 seat, and 3 leg positions), 98% pre-assembled setup, a 13-inch wide seat with extended backrest, and a 1-step foldable space-saving design.',
    image: 'https://m.media-amazon.com/images/I/81pu4FK5uSL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    price: 79.99,
    originalPrice: 89.99,
    rating: 4.5,
    reviews: 987,
    category: 'Compact',
    affiliateLink: 'https://a.co/d/0cJ4WCh3',
  },
];

let currentPageId = 'fashion';
let currentCategory = 'All';
let searchQuery = '';

const heroTitleEl = document.getElementById('heroTitle');
const heroDescriptionEl = document.getElementById('heroDescription');
const heroTaglineEl = document.getElementById('heroTagline');
const categoryPillsEl = document.getElementById('categoryPills');
const productGridEl = document.getElementById('productGrid');
const productsCountEl = document.getElementById('productsCount');
const searchInputEl = document.getElementById('searchInput');
const noResultsEl = document.getElementById('noResults');
const navBtns = document.querySelectorAll('.nav-btn');

function init() {
  setupEventListeners();
  renderPage(currentPageId);
}

function setupEventListeners() {
  navBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      navBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      currentPageId = btn.getAttribute('data-page');
      currentCategory = 'All';
      searchQuery = '';
      searchInputEl.value = '';
      renderPage(currentPageId);
    });
  });

  searchInputEl.addEventListener('input', (e) => {
    searchQuery = e.target.value.toLowerCase().trim();
    renderProducts();
  });
}

function renderPage(pageId) {
  const pageData = PAGES.find(p => p.id === pageId);
  if (!pageData) return;

  heroTaglineEl.innerHTML = `<i class="fa-solid fa-circle-check"></i> ${pageData.tagline}`;
  heroTitleEl.innerHTML = `${pageData.heroTitle} <span class="highlight">${pageData.heroHighlight}</span>`;
  heroDescriptionEl.textContent = pageData.heroDescription;

  renderCategories(pageData.categories);
  renderProducts();
}

function renderCategories(categories) {
  categoryPillsEl.innerHTML = '';
  categories.forEach(cat => {
    const pill = document.createElement('button');
    pill.className = `category-pill ${cat === currentCategory ? 'active' : ''}`;
    pill.textContent = cat;
    pill.addEventListener('click', () => {
      document.querySelectorAll('.category-pill').forEach(p => p.classList.remove('active'));
      pill.classList.add('active');
      currentCategory = cat;
      renderProducts();
    });
    categoryPillsEl.appendChild(pill);
  });
}

function renderProducts() {
  const filtered = PRODUCTS.filter(p => {
    const matchesPage = p.page === currentPageId;
    const matchesCategory = currentCategory === 'All' || p.category === currentCategory;
    const matchesSearch = searchQuery === '' || 
      p.title.toLowerCase().includes(searchQuery) || 
      p.description.toLowerCase().includes(searchQuery) ||
      p.category.toLowerCase().includes(searchQuery);

    return matchesPage && matchesCategory && matchesSearch;
  });

  productsCountEl.textContent = `Showing ${filtered.length} products`;

  if (filtered.length === 0) {
    productGridEl.innerHTML = '';
    noResultsEl.classList.remove('hidden');
    return;
  }

  noResultsEl.classList.add('hidden');
  
  productGridEl.innerHTML = filtered.map(product => `
    <div class="product-card">
      <div class="card-image-wrap">
        <img src="${product.image}" alt="${product.title}" class="card-image" loading="lazy">
        ${product.featured ? '<span class="badge-featured">Featured</span>' : ''}
      </div>
      <div class="card-body">
        <span class="card-category">${product.category}</span>
        <h3 class="card-title">${product.title}</h3>
        <p class="card-description">${product.description}</p>
        
        <div class="card-rating">
          <span class="stars"><i class="fa-solid fa-star"></i> ${product.rating}</span>
          <span class="reviews-count">(${product.reviews} reviews)</span>
        </div>

        <div class="card-footer">
          <div class="price-box">
            <span class="current-price">$${product.price.toFixed(2)}</span>
            ${product.originalPrice ? `<span class="original-price">$${product.originalPrice.toFixed(2)}</span>` : ''}
          </div>
          <a href="${product.affiliateLink}" target="_blank" rel="noopener noreferrer" class="cta-button">
            Check on Amazon <i class="fa-solid fa-arrow-up-right-from-square"></i>
          </a>
        </div>
      </div>
    </div>
  `).join('');
}

document.addEventListener('DOMContentLoaded', init);